-- Regras OES/DSS05 exportadas do ambiente do projeto
-- Preserva os valores cadastrados no momento da extração.

INSERT INTO ADMIN.OES_POLITICA_CONSULTA (ID_POLITICA,CODIGO_REGRA,DESCRICAO,TIPO_REGRA,PADRAO,ACAO,ATIVA,CONTROLE_COBIT) VALUES (3,'ESCOPO_ANALITICO','Restringe a Central às perguntas relacionadas ao escopo assistencial do Data Forge.','ESCOPO','ASSISTENCIAL','VALIDAR','S','DSS05');
INSERT INTO ADMIN.OES_POLITICA_CONSULTA (ID_POLITICA,CODIGO_REGRA,DESCRICAO,TIPO_REGRA,PADRAO,ACAO,ATIVA,CONTROLE_COBIT) VALUES (2,'PROMPT_INJECTION','Bloqueia tentativas explícitas de ignorar regras ou modificar instruções internas.','BLOQUEIO','IGNORE AS REGRAS|IGNORE INSTRUCOES|USE OUTRA TABELA|EXECUTE SQL','BLOQUEAR','S','DSS05');
INSERT INTO ADMIN.OES_POLITICA_CONSULTA (ID_POLITICA,CODIGO_REGRA,DESCRICAO,TIPO_REGRA,PADRAO,ACAO,ATIVA,CONTROLE_COBIT) VALUES (1,'SQL_DESTRUTIVO','Bloqueia comandos SQL destrutivos informados pelo usuário.','BLOQUEIO','DROP|DELETE|TRUNCATE|ALTER|GRANT|REVOKE','BLOQUEAR','S','DSS05');
