-- ===== CNES_LEITOS_2023_2025 =====
CREATE TABLE "ADMIN"."CNES_LEITOS_2023_2025" 
   (	"COMP" DATE ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'COMP'), 
	"REGIAO" VARCHAR2(64) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'REGIAO'), 
	"UF" VARCHAR2(64) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'UF'), 
	"MUNICIPIO" VARCHAR2(64) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'MUNICIPIO'), 
	"CNES" VARCHAR2(64) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'CNES'), 
	"NOME_ESTABELECIMENTO" VARCHAR2(64) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'NOME_ESTABELECIMENTO'), 
	"TP_GESTAO" VARCHAR2(64) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'TP_GESTAO'), 
	"CO_TIPO_UNIDADE" VARCHAR2(64) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'CO_TIPO_UNIDADE'), 
	"DS_TIPO_UNIDADE" VARCHAR2(64) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'DS_TIPO_UNIDADE'), 
	"NATUREZA_JURIDICA" NUMBER ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'NATUREZA_JURIDICA'), 
	"DESC_NATUREZA_JURIDICA" VARCHAR2(64) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'DESC_NATUREZA_JURIDICA'), 
	"CO_CEP" VARCHAR2(64) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'CO_CEP'), 
	"LEITOS_EXISTENTES" NUMBER ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'LEITOS_EXISTENTES'), 
	"LEITOS_SUS" NUMBER ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'LEITOS_SUS'), 
	"UTI_TOTAL_EXIST" NUMBER ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'UTI_TOTAL_EXIST'), 
	"UTI_TOTAL_SUS" NUMBER ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'UTI_TOTAL_SUS'), 
	"UTI_ADULTO_EXIST" NUMBER ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'UTI_ADULTO_EXIST'), 
	"UTI_ADULTO_SUS" NUMBER ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'UTI_ADULTO_SUS'), 
	"UTI_PEDIATRICO_EXIST" NUMBER ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'UTI_PEDIATRICO_EXIST'), 
	"UTI_PEDIATRICO_SUS" NUMBER ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'UTI_PEDIATRICO_SUS'), 
	"UTI_NEONATAL_EXIST" NUMBER ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'UTI_NEONATAL_EXIST'), 
	"UTI_NEONATAL_SUS" NUMBER ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'UTI_NEONATAL_SUS'), 
	"UTI_QUEIMADO_EXIST" NUMBER ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'UTI_QUEIMADO_EXIST'), 
	"UTI_QUEIMADO_SUS" NUMBER ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'UTI_QUEIMADO_SUS'), 
	"UTI_CORONARIANA_EXIST" NUMBER ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'UTI_CORONARIANA_EXIST'), 
	"UTI_CORONARIANA_SUS" NUMBER ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'UTI_CORONARIANA_SUS'), 
	"ANO_REF" NUMBER ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'ANO_REF'), 
	"CO_IBGE" VARCHAR2(64) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'CO_IBGE'), 
	"DESABILITADO" BOOLEAN ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'DESABILITADO'), 
	"NOME_UF" VARCHAR2(64) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'NOME_UF'), 
	"PORTE" VARCHAR2(64) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'PORTE')
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA";


-- ===== DATASET_UNIFICADO_UF_2023_2025 =====
CREATE TABLE "ADMIN"."DATASET_UNIFICADO_UF_2023_2025" 
   (	"NOME_UF" VARCHAR2(64) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'NOME_UF'), 
	"CO_UF_IBGE" NUMBER ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'CO_UF_IBGE'), 
	"ANO" NUMBER ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Ano'), 
	"LEITOS_SUS" NUMBER ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Leitos SUS'), 
	"LEITOS_UTI_TOTAL" NUMBER ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Leitos UTI total'), 
	"LEITOS_EXISTENTES" NUMBER ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Leitos existentes'), 
	"POPULAÇÃO_RESIDENTE" NUMBER ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'População residente'), 
	"QTD_HOSPITAIS" NUMBER ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'Qtd hospitais'), 
	"TOTAL_INTERNACOES" NUMBER ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'TOTAL_INTERNACOES'), 
	"TOTAL_OBITOS_SIH" NUMBER ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'TOTAL_OBITOS_SIH'), 
	"VALOR_TOTAL_SIH" NUMBER ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'VALOR_TOTAL_SIH'), 
	"MEDIA_PERMANENCIA_ANO" NUMBER ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'MEDIA_PERMANENCIA_ANO'), 
	"LEITOS_POR_10K_HAB" NUMBER ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'LEITOS_POR_10K_HAB'), 
	"INTERNACOES_POR_LEITO" NUMBER ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'INTERNACOES_POR_LEITO'), 
	"TAXA_MORTALIDADE_HOSPITALAR" NUMBER ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'TAXA_MORTALIDADE_HOSPITALAR'), 
	"GASTO_MEDIO_INTERNACAO" NUMBER ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'GASTO_MEDIO_INTERNACAO')
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA";


-- ===== IBGE_POPULACAO_UF_2023_2025 =====
CREATE TABLE "ADMIN"."IBGE_POPULACAO_UF_2023_2025" 
   (	"POPULACAO" NUMBER ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'POPULACAO'), 
	"CO_UF_IBGE" NUMBER ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'CO_UF_IBGE'), 
	"NOME_UF" VARCHAR2(64) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'NOME_UF'), 
	"ANO_REF" NUMBER ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'ANO_REF')
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA";


-- ===== LEITOS_POPULACAO_UF_2023_2025 =====
CREATE TABLE "ADMIN"."LEITOS_POPULACAO_UF_2023_2025" 
   (	"NOME_UF" VARCHAR2(64) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'NOME_UF'), 
	"ANO_REF" NUMBER ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'ANO_REF'), 
	"TOTAL_LEITOS_EXISTENTES" NUMBER ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'TOTAL_LEITOS_EXISTENTES'), 
	"TOTAL_LEITOS_SUS" NUMBER ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'TOTAL_LEITOS_SUS'), 
	"QTD_ESTABELECIMENTOS" NUMBER ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'QTD_ESTABELECIMENTOS'), 
	"POPULACAO" NUMBER ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'POPULACAO'), 
	"CO_UF_IBGE" NUMBER ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'CO_UF_IBGE'), 
	"LEITOS_POR_10K_HAB" NUMBER ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'LEITOS_POR_10K_HAB')
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA";


-- ===== OBITOS_SIH_MENSAL_UF_2023_2025 =====
CREATE TABLE "ADMIN"."OBITOS_SIH_MENSAL_UF_2023_2025" 
   (	"OBITOS" NUMBER ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'OBITOS'), 
	"CO_UF_IBGE" NUMBER ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'CO_UF_IBGE'), 
	"NOME_UF" VARCHAR2(64) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'NOME_UF'), 
	"ANO_REF" NUMBER ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'ANO_REF'), 
	"MES_REF" NUMBER ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'MES_REF')
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA";


-- ===== OES_AUDITORIA_DECISAO =====
CREATE TABLE "ADMIN"."OES_AUDITORIA_DECISAO" 
   (	"ID_AUDITORIA" NUMBER GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"DATA_HORA" TIMESTAMP (6) DEFAULT SYSTIMESTAMP NOT NULL ENABLE, 
	"TIPO_EVENTO" VARCHAR2(50) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"INTENCAO" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"PERGUNTA_USUARIO" VARCHAR2(2000) COLLATE "USING_NLS_COMP", 
	"FONTE_ANALITICA" VARCHAR2(200) COLLATE "USING_NLS_COMP", 
	"SQL_GERADO" CLOB COLLATE "USING_NLS_COMP", 
	"STATUS_EXECUCAO" VARCHAR2(30) COLLATE "USING_NLS_COMP", 
	"STATUS_OES" VARCHAR2(50) COLLATE "USING_NLS_COMP", 
	"CONTROLE_COBIT" VARCHAR2(20) COLLATE "USING_NLS_COMP", 
	"REGRA_OES" VARCHAR2(100) COLLATE "USING_NLS_COMP", 
	"VALIDACAO_HUMANA" VARCHAR2(30) COLLATE "USING_NLS_COMP", 
	"TEMPO_RESPOSTA_MS" NUMBER, 
	"MOTIVO_BLOQUEIO" VARCHAR2(1000) COLLATE "USING_NLS_COMP", 
	"CRIADO_POR" VARCHAR2(128) COLLATE "USING_NLS_COMP" DEFAULT USER, 
	 PRIMARY KEY ("ID_AUDITORIA")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" 
 LOB ("SQL_GERADO") STORE AS SECUREFILE (
  TABLESPACE "DATA" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT));


-- ===== OES_POLITICA_CONSULTA =====
CREATE TABLE "ADMIN"."OES_POLITICA_CONSULTA" 
   (	"ID_POLITICA" NUMBER GENERATED BY DEFAULT AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"CODIGO_REGRA" VARCHAR2(50) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"DESCRICAO" VARCHAR2(500) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"TIPO_REGRA" VARCHAR2(30) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"PADRAO" VARCHAR2(500) COLLATE "USING_NLS_COMP", 
	"ACAO" VARCHAR2(30) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"ATIVA" CHAR(1) COLLATE "USING_NLS_COMP" DEFAULT 'S' NOT NULL ENABLE, 
	"CONTROLE_COBIT" VARCHAR2(20) COLLATE "USING_NLS_COMP" DEFAULT 'DSS05', 
	 CONSTRAINT "CK_OES_POLITICA_ATIVA" CHECK (ATIVA IN ('S', 'N')) ENABLE, 
	 PRIMARY KEY ("ID_POLITICA")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA";
