CREATE TABLE "ADMIN"."CNES_LEITOS_2023_2025" 
   (	"COMP" DATE ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'COMP'), 
	"REGIAO" VARCHAR2(64) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'REGIAO'), 
	"UF" VARCHAR2(64) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'UF'), 
	"MUNICIPIO" VARCHAR2(64) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'MUNICIPIO'), 
	"CNES" VARCHAR2(64) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'CNES'), 
	"NOME_ESTABELECIMENTO" VARCHAR2(64) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'NOME_ESTABELECIMENTO'), 
	"TP_GESTAO" VARCHAR2(64) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'TP_GESTAO'), 
	"CO_TIPO_UNIDADE" VARCHAR2(64) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'CO_TIPO_UNIDADE'), 
	"DS_TIPO_UNIDADE" VARCHAR2(64) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'DS_TIPO_UNIDADE'), 
	"NATUREZA_JURIDICA" NUMBER ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'NATUREZA_JURIDICA'), 
	"DESC_NATUREZA_JURIDICA" VARCHAR2(64) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'DESC_NATUREZA_JURIDICA'), 
	"CO_CEP" VARCHAR2(64) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'CO_CEP'), 
	"LEITOS_EXISTENTES" NUMBER ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'LEITOS_EXISTENTES'), 
	"LEITOS_SUS" NUMBER ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'LEITOS_SUS'), 
	"UTI_TOTAL_EXIST" NUMBER ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'UTI_TOTAL_EXIST'), 
	"UTI_TOTAL_SUS" NUMBER ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'UTI_TOTAL_SUS'), 
	"UTI_ADULTO_EXIST" NUMBER ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'UTI_ADULTO_EXIST'), 
	"UTI_ADULTO_SUS" NUMBER ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'UTI_ADULTO_SUS'), 
	"UTI_PEDIATRICO_EXIST" NUMBER ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'UTI_PEDIATRICO_EXIST'), 
	"UTI_PEDIATRICO_SUS" NUMBER ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'UTI_PEDIATRICO_SUS'), 
	"UTI_NEONATAL_EXIST" NUMBER ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'UTI_NEONATAL_EXIST'), 
	"UTI_NEONATAL_SUS" NUMBER ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'UTI_NEONATAL_SUS'), 
	"UTI_QUEIMADO_EXIST" NUMBER ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'UTI_QUEIMADO_EXIST'), 
	"UTI_QUEIMADO_SUS" NUMBER ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'UTI_QUEIMADO_SUS'), 
	"UTI_CORONARIANA_EXIST" NUMBER ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'UTI_CORONARIANA_EXIST'), 
	"UTI_CORONARIANA_SUS" NUMBER ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'UTI_CORONARIANA_SUS'), 
	"ANO_REF" NUMBER ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'ANO_REF'), 
	"CO_IBGE" VARCHAR2(64) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'CO_IBGE'), 
	"DESABILITADO" BOOLEAN ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'DESABILITADO'), 
	"NOME_UF" VARCHAR2(64) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'NOME_UF'), 
	"PORTE" VARCHAR2(64) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'PORTE')
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA";
