CREATE TABLE "ADMIN"."IBGE_POPULACAO_UF_2023_2025" 
   (	"POPULACAO" NUMBER ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'POPULACAO'), 
	"CO_UF_IBGE" NUMBER ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'CO_UF_IBGE'), 
	"NOME_UF" VARCHAR2(64) COLLATE "USING_NLS_COMP" ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'NOME_UF'), 
	"ANO_REF" NUMBER ANNOTATIONS("DATA_TOOLS_INGEST_fieldName" 'ANO_REF')
   )  DEFAULT COLLATION "USING_NLS_COMP" SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA";
