
-- Generated by ORDS REST Data Services 26.2.2.r2041619
-- Schema: ADMIN  Date: Sun Sep 13 11:04:25 2026 
--
        
DECLARE

  l_roles     OWA.VC_ARR;
  l_modules   OWA.VC_ARR;
  l_patterns  OWA.VC_ARR;

BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'admin',
      p_auto_rest_auth      => FALSE);

  ORDS.DEFINE_MODULE(
      p_module_name    => 'dataforge',
      p_base_path      => '/dataforge/',
      p_items_per_page => 25,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'dataforge',
      p_pattern        => 'ai/showsql',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'dataforge',
      p_pattern        => 'ai/showsql',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'DECLARE 
    l_result   CLOB; 
    l_chunk    VARCHAR2(8000); 
    l_offset   PLS_INTEGER := 1; 
 
    l_status   VARCHAR2(30); 
    l_regra    VARCHAR2(100); 
    l_motivo   VARCHAR2(1000); 
 
    l_inicio   TIMESTAMP; 
    l_fim      TIMESTAMP; 
    l_tempo_ms NUMBER; 

    l_erro     VARCHAR2(1000);
BEGIN 
    l_inicio := SYSTIMESTAMP; 
 
    ADMIN.PRC_OES_VALIDAR_CONSULTA( 
        P_PERGUNTA => :pergunta, 
        P_INTENCAO => :intencao, 
        P_STATUS   => l_status, 
        P_REGRA    => l_regra, 
        P_MOTIVO   => l_motivo 
    ); 
 
    IF l_status <> ''PERMITIDO'' THEN 
 
        INSERT INTO ADMIN.OES_AUDITORIA_DECISAO ( 
            TIPO_EVENTO, 
            INTENCAO, 
            PERGUNTA_USUARIO, 
            STATUS_EXECUCAO, 
            CONTROLE_COBIT, 
            REGRA_OES, 
            MOTIVO_BLOQUEIO 
        ) 
        VALUES ( 
            ''SHOWSQL_BLOQUEADO'', 
            :intencao, 
            :pergunta, 
           ' || ' l_status, 
            ''DSS05'', 
            l_regra, 
            l_motivo 
        ); 
 
        COMMIT; 
 
        HTP.PRN( 
            ''{"status":"'' 
            || REPLACE(l_status, ''"'', ''\"'') 
            || ''","regra":"'' 
            || REPLACE(l_regra, ''"'', ''\"'') 
            || ''","motivo":"'' 
            || REPLACE(l_motivo, ''"'', ''\"'') 
            || ''"}'' 
        ); 
 
        RETURN; 
    END IF; 
 
 
    l_result := DBMS_CLOUD_AI.GENERATE( 
        prompt       => :pergunta, 
        profile_name => ''DATA_FORGE_AI'', 
        action       => ''showsql'' 
    ); 
 
    l_fim := SYSTIMESTAMP; 
 
    l_tempo_ms := 
          EXTRACT(DAY    FROM (l_fim - l_inicio)) * 86400000 
        + EXTRACT(HOUR   FROM (l_fim - l_inicio)) * 3600000 
        + EXTRACT(MINUTE FROM (l_fim - l_inicio)) * 60000 
        + EXTRACT(SECOND FROM (l_fim - l_inicio)) * 1000; 
 
 
    INSERT INTO ADMIN.OES_AUDITORIA_DECISAO ( 
        TIPO_EVENTO, 
        INTENC' || 'AO, 
        PERGUNTA_USUARIO, 
        FONTE_ANALITICA, 
        SQL_GERADO, 
        STATUS_EXECUCAO, 
        CONTROLE_COBIT, 
        REGRA_OES, 
        TEMPO_RESPOSTA_MS 
    ) 
    VALUES ( 
        ''SHOWSQL'', 
        :intencao, 
        :pergunta, 
        ''SELECT_AI_SHOWSQL'', 
        l_result, 
        ''SUCESSO'', 
        ''MEA01'', 
        ''RASTREABILIDADE_SQL'', 
        ROUND(l_tempo_ms) 
    ); 
 
    COMMIT; 
 
 
    LOOP 
        l_chunk := DBMS_LOB.SUBSTR( 
            l_result, 
            8000, 
            l_offset 
        ); 
 
        EXIT WHEN l_chunk IS NULL; 
 
        HTP.PRN(l_chunk); 
 
        l_offset := l_offset + LENGTH(l_chunk); 
    END LOOP; 
 
 
EXCEPTION 
    WHEN OTHERS THEN 

        l_erro := SUBSTR(SQLERRM, 1, 1000);
 
        l_fim := SYSTIMESTAMP; 
 
        l_tempo_ms := 
              EXTRACT(DAY    FROM (l_fim - l_inicio)) * 86400000 
            + EXTRACT(HOUR   FROM (l_fim - l_inicio)) * 36' || '00000 
            + EXTRACT(MINUTE FROM (l_fim - l_inicio)) * 60000 
            + EXTRACT(SECOND FROM (l_fim - l_inicio)) * 1000; 
 
        INSERT INTO ADMIN.OES_AUDITORIA_DECISAO ( 
            TIPO_EVENTO, 
            INTENCAO, 
            PERGUNTA_USUARIO, 
            STATUS_EXECUCAO, 
            CONTROLE_COBIT, 
            REGRA_OES, 
            TEMPO_RESPOSTA_MS, 
            MOTIVO_BLOQUEIO 
        ) 
        VALUES ( 
            ''ERRO_SHOWSQL'', 
            :intencao, 
            :pergunta, 
            ''ERRO'', 
            ''MEA01'', 
            ''ERRO_EXECUCAO'', 
            ROUND(l_tempo_ms), 
            l_erro
        ); 
 
        COMMIT; 
 
        HTP.PRN( 
            ''{"status":"ERRO","motivo":"'' 
            || REPLACE(l_erro, ''"'', ''\"'') 
            || ''"}'' 
        ); 
END;');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'dataforge',
      p_pattern            => 'ai/showsql',
      p_method             => 'POST',
      p_name               => 'pergunta',
      p_bind_variable_name => 'pergunta',
      p_source_type        => 'URI',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'dataforge',
      p_pattern        => 'ai/runsql',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'dataforge',
      p_pattern        => 'ai/runsql',
      p_method         => 'POST',
      p_source_type    => 'plsql/block',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'DECLARE
    l_result   CLOB;
    l_chunk    VARCHAR2(8000);
    l_offset   PLS_INTEGER := 1;

    l_status   VARCHAR2(100);
    l_regra    VARCHAR2(1000);
    l_motivo   VARCHAR2(4000);

    l_inicio   TIMESTAMP;
    l_fim      TIMESTAMP;
    l_tempo_ms NUMBER;

    l_erro     VARCHAR2(4000);
BEGIN
    l_inicio := SYSTIMESTAMP;

    ADMIN.PRC_OES_VALIDAR_CONSULTA(
        P_PERGUNTA => :pergunta,
        P_INTENCAO => :intencao,
        P_STATUS   => l_status,
        P_REGRA    => l_regra,
        P_MOTIVO   => l_motivo
    );

    IF l_status <> ''PERMITIDO'' THEN

        BEGIN
            INSERT INTO ADMIN.OES_AUDITORIA_DECISAO (
                TIPO_EVENTO,
                INTENCAO,
                PERGUNTA_USUARIO,
                STATUS_EXECUCAO,
                CONTROLE_COBIT,
                REGRA_OES,
                MOTIVO_BLOQUEIO
            )
            VALUES (
                ''CONSULTA_BLOQUEADA'',
                :intencao,
       ' || '         :pergunta,
                l_status,
                ''DSS05'',
                l_regra,
                l_motivo
            );

            COMMIT;

        EXCEPTION
            WHEN OTHERS THEN
                NULL;
        END;

        HTP.PRN(
            ''{"status":"''
            || REPLACE(NVL(l_status, ''BLOQUEADO''), ''"'', ''\"'')
            || ''","regra":"''
            || REPLACE(NVL(l_regra, ''''), ''"'', ''\"'')
            || ''","motivo":"''
            || REPLACE(NVL(l_motivo, ''''), ''"'', ''\"'')
            || ''"}''
        );

        RETURN;
    END IF;


    l_result := DBMS_CLOUD_AI.GENERATE(
        prompt       => :pergunta,
        profile_name => ''DATA_FORGE_AI'',
        action       => ''runsql''
    );


    l_fim := SYSTIMESTAMP;

    l_tempo_ms :=
          EXTRACT(DAY    FROM (l_fim - l_inicio)) * 86400000
        + EXTRACT(HOUR   FROM (l_fim - l_inicio)) * 3600000
        + EXTRACT(MINUTE FROM (l_fim - l_inicio)) * 60000
    ' || '    + EXTRACT(SECOND FROM (l_fim - l_inicio)) * 1000;


    BEGIN
        INSERT INTO ADMIN.OES_AUDITORIA_DECISAO (
            TIPO_EVENTO,
            INTENCAO,
            PERGUNTA_USUARIO,
            FONTE_ANALITICA,
            STATUS_EXECUCAO,
            CONTROLE_COBIT,
            REGRA_OES,
            TEMPO_RESPOSTA_MS
        )
        VALUES (
            ''CONSULTA'',
            :intencao,
            :pergunta,
            ''SELECT_AI_RUNSQL'',
            ''SUCESSO'',
            ''MEA01'',
            ''AUDITORIA_SELECT_AI'',
            ROUND(l_tempo_ms)
        );

        COMMIT;

    EXCEPTION
        WHEN OTHERS THEN
            NULL;
    END;


    LOOP
        l_chunk := DBMS_LOB.SUBSTR(
            l_result,
            8000,
            l_offset
        );

        EXIT WHEN l_chunk IS NULL;

        HTP.PRN(l_chunk);

        l_offset := l_offset + LENGTH(l_chunk);
    END LOOP;


EXCEPTION
    WHEN OTHERS THEN

     ' || '   l_erro := SUBSTR(SQLERRM, 1, 4000);

        BEGIN
            l_fim := SYSTIMESTAMP;

            l_tempo_ms :=
                  EXTRACT(DAY    FROM (l_fim - l_inicio)) * 86400000
                + EXTRACT(HOUR   FROM (l_fim - l_inicio)) * 3600000
                + EXTRACT(MINUTE FROM (l_fim - l_inicio)) * 60000
                + EXTRACT(SECOND FROM (l_fim - l_inicio)) * 1000;

            INSERT INTO ADMIN.OES_AUDITORIA_DECISAO (
                TIPO_EVENTO,
                INTENCAO,
                PERGUNTA_USUARIO,
                STATUS_EXECUCAO,
                CONTROLE_COBIT,
                REGRA_OES,
                TEMPO_RESPOSTA_MS,
                MOTIVO_BLOQUEIO
            )
            VALUES (
                ''ERRO_CONSULTA'',
                :intencao,
                :pergunta,
                ''ERRO'',
                ''MEA01'',
                ''ERRO_EXECUCAO'',
                ROUND(l_tempo_ms),
                l_erro
            );

  ' || '          COMMIT;

        EXCEPTION
            WHEN OTHERS THEN
                NULL;
        END;


        HTP.PRN(
            ''{"status":"ERRO","motivo":"''
            || REPLACE(
                   REPLACE(
                       REPLACE(
                           NVL(l_erro, ''Erro desconhecido''),
                           ''\'',
                           ''\\''
                       ),
                       ''"'',
                       ''\"''
                   ),
                   CHR(10),
                   '' ''
               )
            || ''"}''
        );
END;');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'dataforge',
      p_pattern            => 'ai/runsql',
      p_method             => 'POST',
      p_name               => 'pergunta',
      p_bind_variable_name => 'pergunta',
      p_source_type        => 'URI',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'dataforge',
      p_pattern        => 'hospitals/',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'dataforge',
      p_pattern        => 'hospitals/',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'SELECT
    NOME_ESTABELECIMENTO,
    MUNICIPIO,
    CNES,
    TIPO_UNIDADE,
    NATUREZA_JURIDICA,
    PORTE,
    LEITOS_SUS,
    UTI_TOTAL_SUS
FROM (
    SELECT
        NOME_ESTABELECIMENTO,
        MUNICIPIO,
        CNES,
        TIPO_UNIDADE,
        NATUREZA_JURIDICA,
        PORTE,
        LEITOS_SUS,
        UTI_TOTAL_SUS,
        ROW_NUMBER() OVER (
            PARTITION BY CNES
            ORDER BY ANO DESC
        ) AS RN
    FROM ADMIN.VW_PERFIL_HOSPITAL
    WHERE UPPER(UF) = UPPER(:uf)
      AND CNES IS NOT NULL
)
WHERE RN = 1
ORDER BY NOME_ESTABELECIMENTO
FETCH FIRST 150 ROWS ONLY');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'dataforge',
      p_pattern            => 'hospitals/',
      p_method             => 'GET',
      p_name               => 'uf',
      p_bind_variable_name => 'uf',
      p_source_type        => 'URI',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'dataforge',
      p_pattern        => 'simulacao/sobrecarga',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'dataforge',
      p_pattern        => 'simulacao/sobrecarga',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page => 25,
      p_mimes_allowed  => NULL,
      p_comments       => NULL,
      p_source         => 
'SELECT
    NOME_UF,
    ANO,
    PERFIL_ASSISTENCIAL,
    INDICE_PRESSAO_ASSISTENCIAL,
    TOTAL_INTERNACOES,
    INTERNACOES_POR_LEITO,
    LEITOS_POR_10K_HAB,
    UTI_SUS_100K,
    MEDIANA_PRESSAO,
    MEDIANA_DEMANDA,
    MEDIANA_LEITOS,
    MEDIANA_UTI,
    PONTO_PRESSAO,
    PONTO_DEMANDA,
    PONTO_LEITOS,
    PONTO_UTI,
    SCORE_SOBRECARGA,
    CENARIO_SOBRECARGA,
    RANK_PRESSAO,
    RANK_CAPACIDADE,
    VARIACAO_PRESSAO_ANUAL,
    VARIACAO_PRESSAO_PERIODO
FROM ADMIN.VW_SIMULACAO_SOBRECARGA
WHERE ANO = :ano
  AND UPPER(NOME_UF) = UPPER(:uf)');

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'dataforge',
      p_pattern            => 'simulacao/sobrecarga',
      p_method             => 'GET',
      p_name               => 'ano',
      p_bind_variable_name => 'ano',
      p_source_type        => 'URI',
      p_param_type         => 'INT',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.DEFINE_PARAMETER(
      p_module_name        => 'dataforge',
      p_pattern            => 'simulacao/sobrecarga',
      p_method             => 'GET',
      p_name               => 'uf',
      p_bind_variable_name => 'uf',
      p_source_type        => 'URI',
      p_param_type         => 'STRING',
      p_access_method      => 'IN',
      p_comments           => NULL);

  ORDS.CREATE_ROLE(
      p_role_name=> 'com.oracle.dbtools.queries.role');
  l_roles(1) := 'com.oracle.dbtools.queries.role';
  l_patterns(1) := '/com.oracle.dbtools.queries/*';
  l_modules(1) := 'dataforge';

  ORDS.DEFINE_PRIVILEGE(
      p_privilege_name => 'com.oracle.dbtools.queries.privilege',
      p_roles          => l_roles,
      p_patterns       => l_patterns,
      p_modules        => l_modules,
      p_label          => 'Protected',
      p_description    => 'Shared queries module privilege protection',
      p_comments       => 'Shared Query object privilege generated'); 

  l_roles.DELETE;
  l_modules.DELETE;
  l_patterns.DELETE;

COMMIT;
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    RAISE;

END;