-- ===== VW_CAPACIDADE_HOSPITALAR =====
CREATE OR REPLACE FORCE EDITIONABLE VIEW "ADMIN"."VW_CAPACIDADE_HOSPITALAR" ("UF", "NOME_UF", "ANO_REF", "QTD_ESTABELECIMENTOS", "LEITOS_EXISTENTES", "LEITOS_SUS", "UTI_TOTAL_EXIST", "UTI_TOTAL_SUS", "UTI_ADULTO_EXIST", "UTI_ADULTO_SUS", "UTI_PEDIATRICO_EXIST", "UTI_PEDIATRICO_SUS", "UTI_NEONATAL_EXIST", "UTI_NEONATAL_SUS", "UTI_QUEIMADO_EXIST", "UTI_QUEIMADO_SUS", "UTI_CORONARIANA_EXIST", "UTI_CORONARIANA_SUS") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  SELECT
    UF,
    NOME_UF,
    ANO_REF,

    COUNT(DISTINCT CNES) AS QTD_ESTABELECIMENTOS,

    SUM(NVL(LEITOS_EXISTENTES, 0)) AS LEITOS_EXISTENTES,
    SUM(NVL(LEITOS_SUS, 0)) AS LEITOS_SUS,

    SUM(NVL(UTI_TOTAL_EXIST, 0)) AS UTI_TOTAL_EXIST,
    SUM(NVL(UTI_TOTAL_SUS, 0)) AS UTI_TOTAL_SUS,

    SUM(NVL(UTI_ADULTO_EXIST, 0)) AS UTI_ADULTO_EXIST,
    SUM(NVL(UTI_ADULTO_SUS, 0)) AS UTI_ADULTO_SUS,

    SUM(NVL(UTI_PEDIATRICO_EXIST, 0)) AS UTI_PEDIATRICO_EXIST,
    SUM(NVL(UTI_PEDIATRICO_SUS, 0)) AS UTI_PEDIATRICO_SUS,

    SUM(NVL(UTI_NEONATAL_EXIST, 0)) AS UTI_NEONATAL_EXIST,
    SUM(NVL(UTI_NEONATAL_SUS, 0)) AS UTI_NEONATAL_SUS,

    SUM(NVL(UTI_QUEIMADO_EXIST, 0)) AS UTI_QUEIMADO_EXIST,
    SUM(NVL(UTI_QUEIMADO_SUS, 0)) AS UTI_QUEIMADO_SUS,

    SUM(NVL(UTI_CORONARIANA_EXIST, 0)) AS UTI_CORONARIANA_EXIST,
    SUM(NVL(UTI_CORONARIANA_SUS, 0)) AS UTI_CORONARIANA_SUS

FROM ADMIN.CNES_LEITOS_2023_2025

WHERE COMP = ADD_MONTHS(
    TO_DATE(ANO_REF || '-01-01', 'YYYY-MM-DD'),
    11
)

GROUP BY
    UF,
    NOME_UF,
    ANO_REF;


-- ===== VW_EVOLUCAO_INDICADORES =====
CREATE OR REPLACE FORCE EDITIONABLE VIEW "ADMIN"."VW_EVOLUCAO_INDICADORES" ("NOME_UF", "INTERNACOES_2023", "INTERNACOES_2025", "VAR_INTERNACOES", "VAR_INTERNACOES_PCT", "LEITOS_SUS_2023", "LEITOS_SUS_2025", "VAR_LEITOS_SUS", "VAR_LEITOS_SUS_PCT", "LEITOS_10K_2023", "LEITOS_10K_2025", "VAR_LEITOS_10K", "VAR_LEITOS_10K_PCT", "UTI_100K_2023", "UTI_100K_2025", "VAR_UTI_100K", "VAR_UTI_100K_PCT", "DEMANDA_LEITO_2023", "DEMANDA_LEITO_2025", "VAR_DEMANDA_LEITO", "VAR_DEMANDA_LEITO_PCT", "MORTALIDADE_2023", "MORTALIDADE_2025", "VAR_MORTALIDADE", "GASTO_MEDIO_2023", "GASTO_MEDIO_2025", "VAR_GASTO_MEDIO", "VAR_GASTO_MEDIO_PCT", "OBITOS_2023", "OBITOS_2025", "VAR_OBITOS", "VAR_OBITOS_PCT") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  SELECT
    T23.NOME_UF,

    /* =========================
       INTERNAÇÕES
       ========================= */
    T23.TOTAL_INTERNACOES AS INTERNACOES_2023,
    T25.TOTAL_INTERNACOES AS INTERNACOES_2025,

    T25.TOTAL_INTERNACOES - T23.TOTAL_INTERNACOES
        AS VAR_INTERNACOES,

    ROUND(
        (T25.TOTAL_INTERNACOES - T23.TOTAL_INTERNACOES)
        / NULLIF(T23.TOTAL_INTERNACOES, 0) * 100,
        2
    ) AS VAR_INTERNACOES_PCT,

    /* =========================
       LEITOS SUS
       ========================= */
    T23.LEITOS_SUS AS LEITOS_SUS_2023,
    T25.LEITOS_SUS AS LEITOS_SUS_2025,

    T25.LEITOS_SUS - T23.LEITOS_SUS
        AS VAR_LEITOS_SUS,

    ROUND(
        (T25.LEITOS_SUS - T23.LEITOS_SUS)
        / NULLIF(T23.LEITOS_SUS, 0) * 100,
        2
    ) AS VAR_LEITOS_SUS_PCT,

    /* =========================
       LEITOS SUS / 10 MIL HAB.
       ========================= */
    T23.LEITOS_POR_10K_HAB AS LEITOS_10K_2023,
    T25.LEITOS_POR_10K_HAB AS LEITOS_10K_2025,

    ROUND(
        T25.LEITOS_POR_10K_HAB - T23.LEITOS_POR_10K_HAB,
        2
    ) AS VAR_LEITOS_10K,

    ROUND(
        (T25.LEITOS_POR_10K_HAB - T23.LEITOS_POR_10K_HAB)
        / NULLIF(T23.LEITOS_POR_10K_HAB, 0) * 100,
        2
    ) AS VAR_LEITOS_10K_PCT,

    /* =========================
       UTI SUS / 100 MIL HAB.
       ========================= */
    T23.UTI_SUS_100K AS UTI_100K_2023,
    T25.UTI_SUS_100K AS UTI_100K_2025,

    ROUND(
        T25.UTI_SUS_100K - T23.UTI_SUS_100K,
        2
    ) AS VAR_UTI_100K,

    ROUND(
        (T25.UTI_SUS_100K - T23.UTI_SUS_100K)
        / NULLIF(T23.UTI_SUS_100K, 0) * 100,
        2
    ) AS VAR_UTI_100K_PCT,

    /* =========================
       DEMANDA POR LEITO
       ========================= */
    T23.INTERNACOES_POR_LEITO AS DEMANDA_LEITO_2023,
    T25.INTERNACOES_POR_LEITO AS DEMANDA_LEITO_2025,

    ROUND(
        T25.INTERNACOES_POR_LEITO - T23.INTERNACOES_POR_LEITO,
        2
    ) AS VAR_DEMANDA_LEITO,

    ROUND(
        (T25.INTERNACOES_POR_LEITO - T23.INTERNACOES_POR_LEITO)
        / NULLIF(T23.INTERNACOES_POR_LEITO, 0) * 100,
        2
    ) AS VAR_DEMANDA_LEITO_PCT,

    /* =========================
       MORTALIDADE
       ========================= */
    T23.TAXA_MORTALIDADE_HOSPITALAR AS MORTALIDADE_2023,
    T25.TAXA_MORTALIDADE_HOSPITALAR AS MORTALIDADE_2025,

    ROUND(
        T25.TAXA_MORTALIDADE_HOSPITALAR
        - T23.TAXA_MORTALIDADE_HOSPITALAR,
        2
    ) AS VAR_MORTALIDADE,

    /* =========================
       GASTO MÉDIO
       ========================= */
    T23.GASTO_MEDIO_INTERNACAO AS GASTO_MEDIO_2023,
    T25.GASTO_MEDIO_INTERNACAO AS GASTO_MEDIO_2025,

    ROUND(
        T25.GASTO_MEDIO_INTERNACAO
        - T23.GASTO_MEDIO_INTERNACAO,
        2
    ) AS VAR_GASTO_MEDIO,

    ROUND(
        (T25.GASTO_MEDIO_INTERNACAO - T23.GASTO_MEDIO_INTERNACAO)
        / NULLIF(T23.GASTO_MEDIO_INTERNACAO, 0) * 100,
        2
    ) AS VAR_GASTO_MEDIO_PCT,

    /* =========================
       ÓBITOS SIH
       ========================= */
    O23.OBITOS_2023,
    O25.OBITOS_2025,

    O25.OBITOS_2025 - O23.OBITOS_2023
        AS VAR_OBITOS,

    ROUND(
        (O25.OBITOS_2025 - O23.OBITOS_2023)
        / NULLIF(O23.OBITOS_2023, 0) * 100,
        2
    ) AS VAR_OBITOS_PCT

FROM
    ADMIN.VW_INDICADORES_TERRITORIAIS T23

JOIN
    ADMIN.VW_INDICADORES_TERRITORIAIS T25
    ON T25.NOME_UF = T23.NOME_UF
   AND T25.ANO = 2025

JOIN
(
    SELECT
        NOME_UF,
        SUM(OBITOS) AS OBITOS_2023
    FROM ADMIN.VW_OBITOS_MENSAIS
    WHERE ANO_REF = 2023
    GROUP BY NOME_UF
) O23
    ON O23.NOME_UF = T23.NOME_UF

JOIN
(
    SELECT
        NOME_UF,
        SUM(OBITOS) AS OBITOS_2025
    FROM ADMIN.VW_OBITOS_MENSAIS
    WHERE ANO_REF = 2025
    GROUP BY NOME_UF
) O25
    ON O25.NOME_UF = T23.NOME_UF

WHERE
    T23.ANO = 2023;


-- ===== VW_EVOLUCAO_PERFIL_ASSISTENCIAL =====
CREATE OR REPLACE FORCE EDITIONABLE VIEW "ADMIN"."VW_EVOLUCAO_PERFIL_ASSISTENCIAL" ("PERFIL_ASSISTENCIAL", "QTD_UFS_2023", "QTD_UFS_2025", "VARIACAO_UFS", "TENDENCIA") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  WITH CONTAGEM AS (
    SELECT
        PERFIL_ASSISTENCIAL,
        ANO,
        COUNT(*) AS QTD_UFS
    FROM ADMIN.VW_PERFIL_ASSISTENCIAL
    WHERE ANO IN (2023, 2025)
    GROUP BY
        PERFIL_ASSISTENCIAL,
        ANO
)

SELECT
    PERFIL_ASSISTENCIAL,

    NVL(
        MAX(CASE
            WHEN ANO = 2023 THEN QTD_UFS
        END),
        0
    ) AS QTD_UFS_2023,

    NVL(
        MAX(CASE
            WHEN ANO = 2025 THEN QTD_UFS
        END),
        0
    ) AS QTD_UFS_2025,

    NVL(
        MAX(CASE
            WHEN ANO = 2025 THEN QTD_UFS
        END),
        0
    )
    -
    NVL(
        MAX(CASE
            WHEN ANO = 2023 THEN QTD_UFS
        END),
        0
    ) AS VARIACAO_UFS,

    CASE
        WHEN
            NVL(MAX(CASE
                WHEN ANO = 2025 THEN QTD_UFS
            END), 0)
            >
            NVL(MAX(CASE
                WHEN ANO = 2023 THEN QTD_UFS
            END), 0)
        THEN 'CRESCENTE'

        WHEN
            NVL(MAX(CASE
                WHEN ANO = 2025 THEN QTD_UFS
            END), 0)
            <
            NVL(MAX(CASE
                WHEN ANO = 2023 THEN QTD_UFS
            END), 0)
        THEN 'DECRESCENTE'

        ELSE 'ESTAVEL'
    END AS TENDENCIA

FROM CONTAGEM

GROUP BY
    PERFIL_ASSISTENCIAL;


-- ===== VW_INDICADORES_TERRITORIAIS =====
CREATE OR REPLACE FORCE EDITIONABLE VIEW "ADMIN"."VW_INDICADORES_TERRITORIAIS" ("NOME_UF", "ANO", "TOTAL_INTERNACOES", "MEDIA_PERMANENCIA_ANO", "LEITOS_SUS", "LEITOS_POR_10K_HAB", "INTERNACOES_POR_LEITO", "TAXA_MORTALIDADE_HOSPITALAR", "GASTO_MEDIO_INTERNACAO", "QTD_ESTABELECIMENTOS", "LEITOS_EXISTENTES", "LEITOS_SUS_CNES", "UTI_TOTAL_EXIST", "UTI_TOTAL_SUS", "POPULACAO", "UTI_SUS_100K") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  SELECT
    D.NOME_UF,
    D.ANO,

    -- Demanda
    D.TOTAL_INTERNACOES,
    D.MEDIA_PERMANENCIA_ANO,

    -- Indicadores já existentes no dataset
    D.LEITOS_SUS,
    D.LEITOS_POR_10K_HAB,
    D.INTERNACOES_POR_LEITO,
    D.TAXA_MORTALIDADE_HOSPITALAR,
    D.GASTO_MEDIO_INTERNACAO,

    -- Capacidade CNES
    C.QTD_ESTABELECIMENTOS,
    C.LEITOS_EXISTENTES,
    C.LEITOS_SUS AS LEITOS_SUS_CNES,
    C.UTI_TOTAL_EXIST,
    C.UTI_TOTAL_SUS,

    -- População oficial IBGE
    P.POPULACAO,

    -- Novo indicador
    ROUND(
        C.UTI_TOTAL_SUS / NULLIF(P.POPULACAO, 0) * 100000,
        2
    ) AS UTI_SUS_100K

FROM ADMIN.DATASET_UNIFICADO_UF_2023_2025 D

JOIN ADMIN.VW_CAPACIDADE_HOSPITALAR C
    ON UPPER(TRIM(C.NOME_UF)) = UPPER(TRIM(D.NOME_UF))
   AND C.ANO_REF = D.ANO

JOIN ADMIN.IBGE_POPULACAO_UF_2023_2025 P
    ON P.CO_UF_IBGE = D.CO_UF_IBGE
   AND P.ANO_REF = D.ANO;


-- ===== VW_INTELIGENCIA_ASSISTENCIAL =====
CREATE OR REPLACE FORCE EDITIONABLE VIEW "ADMIN"."VW_INTELIGENCIA_ASSISTENCIAL" ("NOME_UF", "ANO", "PERFIL_ASSISTENCIAL", "INDICE_PRESSAO_ASSISTENCIAL", "TOTAL_INTERNACOES", "INTERNACOES_POR_LEITO", "LEITOS_POR_10K_HAB", "UTI_SUS_100K", "LEITOS_SUS_CNES", "MEDIANA_PRESSAO", "MEDIANA_DEMANDA", "MEDIANA_LEITOS", "MEDIANA_UTI", "PONTO_PRESSAO_SOBRECARGA", "PONTO_DEMANDA_SOBRECARGA", "PONTO_LEITOS_SOBRECARGA", "PONTO_UTI_SOBRECARGA", "SCORE_SOBRECARGA", "CENARIO_SOBRECARGA", "RANK_PRESSAO", "RANK_CAPACIDADE_SOBRECARGA", "VARIACAO_PRESSAO_ANUAL", "VARIACAO_PRESSAO_PERIODO", "PONTO_PRESSAO_CAPACIDADE", "PONTO_DEMANDA_CAPACIDADE", "PONTO_LEITOS_CAPACIDADE", "PONTO_UTI_CAPACIDADE", "SCORE_SUBUTILIZACAO", "SCORE_CAPACIDADE", "CENARIO_CAPACIDADE", "RANK_MAIOR_CAPACIDADE", "RANK_MENOR_CAPACIDADE") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  WITH SOBRECARGA AS (
    SELECT
        NOME_UF,
        ANO,
        PERFIL_ASSISTENCIAL,
        INDICE_PRESSAO_ASSISTENCIAL,
        TOTAL_INTERNACOES,
        INTERNACOES_POR_LEITO,
        LEITOS_POR_10K_HAB,
        UTI_SUS_100K,

        MEDIANA_PRESSAO,
        MEDIANA_DEMANDA,
        MEDIANA_LEITOS,
        MEDIANA_UTI,

        PONTO_PRESSAO,
        PONTO_DEMANDA,
        PONTO_LEITOS,
        PONTO_UTI,

        SCORE_SOBRECARGA,
        CENARIO_SOBRECARGA,
        RANK_PRESSAO,
        RANK_CAPACIDADE,

        VARIACAO_PRESSAO_ANUAL,
        VARIACAO_PRESSAO_PERIODO

    FROM ADMIN.VW_SIMULACAO_SOBRECARGA
),

CAPACIDADE AS (
    SELECT
        NOME_UF,
        ANO,

        PERFIL_ASSISTENCIAL,
        INDICE_PRESSAO_ASSISTENCIAL,
        TOTAL_INTERNACOES,
        LEITOS_SUS_CNES,
        LEITOS_POR_10K_HAB,
        UTI_SUS_100K,
        INTERNACOES_POR_LEITO,

        PONTO_PRESSAO,
        PONTO_DEMANDA,
        PONTO_LEITOS,
        PONTO_UTI,

        SCORE_SUBUTILIZACAO,
        SCORE_CAPACIDADE,
        CENARIO_SUBUTILIZACAO,

        RANK_MAIOR_CAPACIDADE,
        RANK_MENOR_CAPACIDADE

    FROM ADMIN.VW_SIMULACAO_SUBUTILIZACAO
)

SELECT
    S.NOME_UF,
    S.ANO,

    /* Contexto assistencial */
    COALESCE(
        S.PERFIL_ASSISTENCIAL,
        C.PERFIL_ASSISTENCIAL
    ) AS PERFIL_ASSISTENCIAL,

    COALESCE(
        S.INDICE_PRESSAO_ASSISTENCIAL,
        C.INDICE_PRESSAO_ASSISTENCIAL
    ) AS INDICE_PRESSAO_ASSISTENCIAL,

    COALESCE(
        S.TOTAL_INTERNACOES,
        C.TOTAL_INTERNACOES
    ) AS TOTAL_INTERNACOES,

    COALESCE(
        S.INTERNACOES_POR_LEITO,
        C.INTERNACOES_POR_LEITO
    ) AS INTERNACOES_POR_LEITO,

    COALESCE(
        S.LEITOS_POR_10K_HAB,
        C.LEITOS_POR_10K_HAB
    ) AS LEITOS_POR_10K_HAB,

    COALESCE(
        S.UTI_SUS_100K,
        C.UTI_SUS_100K
    ) AS UTI_SUS_100K,

    C.LEITOS_SUS_CNES,

    /* Sobrecarga */
    S.MEDIANA_PRESSAO,
    S.MEDIANA_DEMANDA,
    S.MEDIANA_LEITOS,
    S.MEDIANA_UTI,

    S.PONTO_PRESSAO AS PONTO_PRESSAO_SOBRECARGA,
    S.PONTO_DEMANDA AS PONTO_DEMANDA_SOBRECARGA,
    S.PONTO_LEITOS AS PONTO_LEITOS_SOBRECARGA,
    S.PONTO_UTI AS PONTO_UTI_SOBRECARGA,

    S.SCORE_SOBRECARGA,
    S.CENARIO_SOBRECARGA,
    S.RANK_PRESSAO,
    S.RANK_CAPACIDADE AS RANK_CAPACIDADE_SOBRECARGA,

    S.VARIACAO_PRESSAO_ANUAL,
    S.VARIACAO_PRESSAO_PERIODO,

    /* Capacidade relativa */
    C.PONTO_PRESSAO AS PONTO_PRESSAO_CAPACIDADE,
    C.PONTO_DEMANDA AS PONTO_DEMANDA_CAPACIDADE,
    C.PONTO_LEITOS AS PONTO_LEITOS_CAPACIDADE,
    C.PONTO_UTI AS PONTO_UTI_CAPACIDADE,

    C.SCORE_SUBUTILIZACAO,
    C.SCORE_CAPACIDADE,

    C.CENARIO_SUBUTILIZACAO
        AS CENARIO_CAPACIDADE,

    C.RANK_MAIOR_CAPACIDADE,
    C.RANK_MENOR_CAPACIDADE

FROM SOBRECARGA S

LEFT JOIN CAPACIDADE C
    ON C.NOME_UF = S.NOME_UF
   AND C.ANO = S.ANO;


-- ===== VW_OBITOS_MENSAIS =====
CREATE OR REPLACE FORCE EDITIONABLE VIEW "ADMIN"."VW_OBITOS_MENSAIS" ("CO_UF_IBGE", "NOME_UF", "ANO_REF", "MES_REF", "OBITOS") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  SELECT
    CO_UF_IBGE,
    NOME_UF,
    ANO_REF,
    MES_REF,
    OBITOS
FROM ADMIN.OBITOS_SIH_MENSAL_UF_2023_2025;


-- ===== VW_OES_MONITORAMENTO =====
CREATE OR REPLACE FORCE EDITIONABLE VIEW "ADMIN"."VW_OES_MONITORAMENTO" ("DATA_REF", "TOTAL_EVENTOS", "CONSULTAS_SUCESSO", "CONSULTAS_BLOQUEADAS", "CONSULTAS_ERRO", "TEMPO_MEDIO_RESPOSTA_MS", "DECISOES_VALIDACAO_HUMANA", "EVENTOS_APO12", "EVENTOS_DSS05", "EVENTOS_MEA01", "TAXA_SUCESSO_PCT", "TAXA_BLOQUEIO_PCT", "TAXA_ERRO_PCT", "CONTROLE_COBIT_MONITORAMENTO") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  WITH BASE AS (
    SELECT
        TRUNC(DATA_HORA) AS DATA_REF,
        INTENCAO,
        TIPO_EVENTO,
        STATUS_EXECUCAO,
        STATUS_OES,
        CONTROLE_COBIT,
        VALIDACAO_HUMANA,
        TEMPO_RESPOSTA_MS
    FROM ADMIN.OES_AUDITORIA_DECISAO
),

RESUMO AS (
    SELECT
        DATA_REF,

        COUNT(*) AS TOTAL_EVENTOS,

        SUM(
            CASE
                WHEN STATUS_EXECUCAO = 'SUCESSO'
                THEN 1 ELSE 0
            END
        ) AS CONSULTAS_SUCESSO,

        SUM(
            CASE
                WHEN STATUS_EXECUCAO = 'BLOQUEADO'
                THEN 1 ELSE 0
            END
        ) AS CONSULTAS_BLOQUEADAS,

        SUM(
            CASE
                WHEN STATUS_EXECUCAO = 'ERRO'
                THEN 1 ELSE 0
            END
        ) AS CONSULTAS_ERRO,

        ROUND(
            AVG(
                CASE
                    WHEN STATUS_EXECUCAO = 'SUCESSO'
                    THEN TEMPO_RESPOSTA_MS
                END
            ),
            2
        ) AS TEMPO_MEDIO_RESPOSTA_MS,

        SUM(
            CASE
                WHEN VALIDACAO_HUMANA = 'OBRIGATORIA'
                  OR VALIDACAO_HUMANA = 'VALIDACAO_HUMANA_OBRIGATORIA'
                THEN 1 ELSE 0
            END
        ) AS DECISOES_VALIDACAO_HUMANA,

        SUM(
            CASE
                WHEN CONTROLE_COBIT = 'APO12'
                THEN 1 ELSE 0
            END
        ) AS EVENTOS_APO12,

        SUM(
            CASE
                WHEN CONTROLE_COBIT = 'DSS05'
                THEN 1 ELSE 0
            END
        ) AS EVENTOS_DSS05,

        SUM(
            CASE
                WHEN CONTROLE_COBIT = 'MEA01'
                THEN 1 ELSE 0
            END
        ) AS EVENTOS_MEA01

    FROM BASE
    GROUP BY DATA_REF
)

SELECT
    R."DATA_REF",R."TOTAL_EVENTOS",R."CONSULTAS_SUCESSO",R."CONSULTAS_BLOQUEADAS",R."CONSULTAS_ERRO",R."TEMPO_MEDIO_RESPOSTA_MS",R."DECISOES_VALIDACAO_HUMANA",R."EVENTOS_APO12",R."EVENTOS_DSS05",R."EVENTOS_MEA01",

    ROUND(
        CONSULTAS_SUCESSO
        / NULLIF(TOTAL_EVENTOS, 0)
        * 100,
        2
    ) AS TAXA_SUCESSO_PCT,

    ROUND(
        CONSULTAS_BLOQUEADAS
        / NULLIF(TOTAL_EVENTOS, 0)
        * 100,
        2
    ) AS TAXA_BLOQUEIO_PCT,

    ROUND(
        CONSULTAS_ERRO
        / NULLIF(TOTAL_EVENTOS, 0)
        * 100,
        2
    ) AS TAXA_ERRO_PCT,

    'MEA01' AS CONTROLE_COBIT_MONITORAMENTO

FROM RESUMO R;


-- ===== VW_OES_PRIORIZACAO =====
CREATE OR REPLACE FORCE EDITIONABLE VIEW "ADMIN"."VW_OES_PRIORIZACAO" ("NOME_UF", "ANO", "INDICE_PRESSAO_ASSISTENCIAL", "TOTAL_INTERNACOES", "INTERNACOES_POR_LEITO", "LEITOS_POR_10K_HAB", "UTI_SUS_100K", "SCORE_SOBRECARGA", "CENARIO_SOBRECARGA", "RANK_PRESSAO", "SCORE_CAPACIDADE", "CENARIO_CAPACIDADE", "RANK_MAIOR_CAPACIDADE", "RANK_MENOR_CAPACIDADE", "PONTO_PRESSAO_SOBRECARGA", "PONTO_DEMANDA_SOBRECARGA", "PONTO_LEITOS_SOBRECARGA", "PONTO_UTI_SOBRECARGA", "VARIACAO_PRESSAO_ANUAL", "VARIACAO_PRESSAO_PERIODO", "PONTOS_PRESSAO", "PONTOS_SOBRECARGA", "PONTOS_DEMANDA", "PONTOS_LEITOS", "PONTOS_UTI", "PONTOS_CAPACIDADE", "PONTOS_TENDENCIA", "SCORE_PRIORIDADE", "NIVEL_PRIORIDADE", "RANK_PRIORIDADE", "FATORES_RISCO", "FATORES_ATENUANTES", "FATORES_PRIORIZACAO", "JUSTIFICATIVA_PRIORIDADE", "CONTROLE_COBIT", "REGRA_OES") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  WITH BASE AS (
    SELECT
        NOME_UF,
        ANO,

        INDICE_PRESSAO_ASSISTENCIAL,
        TOTAL_INTERNACOES,
        INTERNACOES_POR_LEITO,
        LEITOS_POR_10K_HAB,
        UTI_SUS_100K,

        SCORE_SOBRECARGA,
        CENARIO_SOBRECARGA,
        RANK_PRESSAO,

        SCORE_CAPACIDADE,
        CENARIO_CAPACIDADE,
        RANK_MAIOR_CAPACIDADE,
        RANK_MENOR_CAPACIDADE,

        PONTO_PRESSAO_SOBRECARGA,
        PONTO_DEMANDA_SOBRECARGA,
        PONTO_LEITOS_SOBRECARGA,
        PONTO_UTI_SOBRECARGA,

        VARIACAO_PRESSAO_ANUAL,
        VARIACAO_PRESSAO_PERIODO

    FROM ADMIN.VW_INTELIGENCIA_ASSISTENCIAL
),

COMPONENTES AS (
    SELECT
        B.*,

        CASE
            WHEN RANK_PRESSAO <= 5 THEN 2
            ELSE 0
        END AS PONTOS_PRESSAO,

        CASE
            WHEN SCORE_SOBRECARGA >= 3 THEN 2
            ELSE 0
        END AS PONTOS_SOBRECARGA,

        CASE
            WHEN PONTO_DEMANDA_SOBRECARGA = 1 THEN 1
            ELSE 0
        END AS PONTOS_DEMANDA,

        CASE
            WHEN PONTO_LEITOS_SOBRECARGA = 1 THEN 1
            ELSE 0
        END AS PONTOS_LEITOS,

        CASE
            WHEN PONTO_UTI_SOBRECARGA = 1 THEN 1
            ELSE 0
        END AS PONTOS_UTI,

        CASE
            WHEN RANK_MENOR_CAPACIDADE <= 5 THEN 2
            ELSE 0
        END AS PONTOS_CAPACIDADE,

        CASE
            WHEN VARIACAO_PRESSAO_ANUAL >= 10 THEN 2
            WHEN VARIACAO_PRESSAO_ANUAL >= 3 THEN 1
            WHEN VARIACAO_PRESSAO_ANUAL <= -10 THEN -1
            ELSE 0
        END AS PONTOS_TENDENCIA

    FROM BASE B
),

SCORE AS (
    SELECT
        C.*,

        (
            PONTOS_PRESSAO
          + PONTOS_SOBRECARGA
          + PONTOS_DEMANDA
          + PONTOS_LEITOS
          + PONTOS_UTI
          + PONTOS_CAPACIDADE
          + PONTOS_TENDENCIA
        ) AS SCORE_PRIORIDADE

    FROM COMPONENTES C
),

CLASSIFICACAO AS (
    SELECT
        S.*,

        CASE
            WHEN SCORE_PRIORIDADE >= 8 THEN 'PRIORIDADE_MUITO_ALTA'
            WHEN SCORE_PRIORIDADE >= 6 THEN 'PRIORIDADE_ALTA'
            WHEN SCORE_PRIORIDADE >= 4 THEN 'PRIORIDADE_MODERADA'
            ELSE 'PRIORIDADE_BAIXA'
        END AS NIVEL_PRIORIDADE

    FROM SCORE S
),

RANKING AS (
    SELECT
        C.*,

        ROW_NUMBER() OVER (
            PARTITION BY ANO
            ORDER BY
                SCORE_PRIORIDADE DESC,
                RANK_PRESSAO ASC,
                RANK_MENOR_CAPACIDADE ASC,
                NOME_UF ASC
        ) AS RANK_PRIORIDADE

    FROM CLASSIFICACAO C
)

SELECT
    R."NOME_UF",R."ANO",R."INDICE_PRESSAO_ASSISTENCIAL",R."TOTAL_INTERNACOES",R."INTERNACOES_POR_LEITO",R."LEITOS_POR_10K_HAB",R."UTI_SUS_100K",R."SCORE_SOBRECARGA",R."CENARIO_SOBRECARGA",R."RANK_PRESSAO",R."SCORE_CAPACIDADE",R."CENARIO_CAPACIDADE",R."RANK_MAIOR_CAPACIDADE",R."RANK_MENOR_CAPACIDADE",R."PONTO_PRESSAO_SOBRECARGA",R."PONTO_DEMANDA_SOBRECARGA",R."PONTO_LEITOS_SOBRECARGA",R."PONTO_UTI_SOBRECARGA",R."VARIACAO_PRESSAO_ANUAL",R."VARIACAO_PRESSAO_PERIODO",R."PONTOS_PRESSAO",R."PONTOS_SOBRECARGA",R."PONTOS_DEMANDA",R."PONTOS_LEITOS",R."PONTOS_UTI",R."PONTOS_CAPACIDADE",R."PONTOS_TENDENCIA",R."SCORE_PRIORIDADE",R."NIVEL_PRIORIDADE",R."RANK_PRIORIDADE",

    /* =========================
       FATORES QUE AUMENTAM RISCO
       ========================= */
    RTRIM(
          CASE
              WHEN PONTOS_PRESSAO > 0
              THEN 'alta pressão assistencial | '
              ELSE ''
          END

       || CASE
              WHEN PONTOS_SOBRECARGA > 0
              THEN 'sobrecarga estrutural elevada | '
              ELSE ''
          END

       || CASE
              WHEN PONTOS_DEMANDA > 0
              THEN 'demanda elevada | '
              ELSE ''
          END

       || CASE
              WHEN PONTOS_LEITOS > 0
              THEN 'baixa disponibilidade relativa de leitos | '
              ELSE ''
          END

       || CASE
              WHEN PONTOS_UTI > 0
              THEN 'baixa disponibilidade relativa de UTI | '
              ELSE ''
          END

       || CASE
              WHEN PONTOS_CAPACIDADE > 0
              THEN 'baixa capacidade relativa | '
              ELSE ''
          END

       || CASE
              WHEN PONTOS_TENDENCIA = 2
              THEN 'forte piora anual da pressão | '
              WHEN PONTOS_TENDENCIA = 1
              THEN 'piora anual da pressão | '
              ELSE ''
          END,

        ' |'
    ) AS FATORES_RISCO,

    /* =========================
       FATORES QUE ATENUAM RISCO
       ========================= */
    RTRIM(
        CASE
            WHEN PONTOS_TENDENCIA = -1
            THEN 'forte melhora anual da pressão | '
            ELSE ''
        END,
        ' |'
    ) AS FATORES_ATENUANTES,

    /* Mantido para compatibilidade */
    RTRIM(
          CASE
              WHEN PONTOS_PRESSAO > 0
              THEN 'alta pressão assistencial | '
              ELSE ''
          END

       || CASE
              WHEN PONTOS_SOBRECARGA > 0
              THEN 'sobrecarga estrutural elevada | '
              ELSE ''
          END

       || CASE
              WHEN PONTOS_DEMANDA > 0
              THEN 'demanda elevada | '
              ELSE ''
          END

       || CASE
              WHEN PONTOS_LEITOS > 0
              THEN 'baixa disponibilidade relativa de leitos | '
              ELSE ''
          END

       || CASE
              WHEN PONTOS_UTI > 0
              THEN 'baixa disponibilidade relativa de UTI | '
              ELSE ''
          END

       || CASE
              WHEN PONTOS_CAPACIDADE > 0
              THEN 'baixa capacidade relativa | '
              ELSE ''
          END

       || CASE
              WHEN PONTOS_TENDENCIA = 2
              THEN 'forte piora anual da pressão | '
              WHEN PONTOS_TENDENCIA = 1
              THEN 'piora anual da pressão | '
              WHEN PONTOS_TENDENCIA = -1
              THEN 'forte melhora anual da pressão | '
              ELSE ''
          END,

        ' |'
    ) AS FATORES_PRIORIZACAO,

    'Pressão: posição '
        || RANK_PRESSAO
        || ' de 27; capacidade desfavorável: posição '
        || RANK_MENOR_CAPACIDADE
        || ' de 27; score de sobrecarga: '
        || SCORE_SOBRECARGA
        || '/4; variação anual da pressão: '
        || ROUND(VARIACAO_PRESSAO_ANUAL, 2)
        || '.'
        AS JUSTIFICATIVA_PRIORIDADE,

    'APO12' AS CONTROLE_COBIT,

    'MITIGACAO_VIES_MULTIFATORIAL' AS REGRA_OES

FROM RANKING R;


-- ===== VW_OES_REALOCACAO =====
CREATE OR REPLACE FORCE EDITIONABLE VIEW "ADMIN"."VW_OES_REALOCACAO" ("ANO", "UF_RECEPTORA", "RANK_PRIORIDADE_RECEPTORA", "SCORE_PRIORIDADE_RECEPTORA", "NIVEL_PRIORIDADE_RECEPTORA", "RANK_PRESSAO_RECEPTORA", "UF_APOIADORA", "RANK_MAIOR_CAPACIDADE", "RANK_MENOR_CAPACIDADE", "SCORE_CAPACIDADE", "CENARIO_CAPACIDADE", "RANK_PRESSAO_APOIADORA", "SCORE_SOBRECARGA_APOIADORA", "RANK_PRIORIDADE_APOIADORA", "SCORE_PRIORIDADE_APOIADORA", "NIVEL_PRIORIDADE_APOIADORA", "LEITOS_APOIADORA", "UTI_APOIADORA", "PONTO_LEITOS_SOBRECARGA", "PONTO_UTI_SOBRECARGA", "RISCO_PRESSAO", "RISCO_PRIORIDADE", "RISCO_UTI", "RISCO_LEITOS", "RISCO_CAPACIDADE", "SCORE_RISCO_REALOCACAO", "STATUS_OES", "RANK_APOIO_OES", "JUSTIFICATIVA_OES", "FATORES_RISCO_REALOCACAO", "CONTROLE_COBIT", "REGRA_OES", "VALIDACAO_FINAL") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  WITH RECEPTORES AS (
    SELECT
        NOME_UF,
        ANO,
        RANK_PRIORIDADE,
        SCORE_PRIORIDADE,
        NIVEL_PRIORIDADE,
        RANK_PRESSAO,
        SCORE_SOBRECARGA,
        CENARIO_SOBRECARGA,
        FATORES_RISCO,
        FATORES_ATENUANTES
    FROM ADMIN.VW_OES_PRIORIZACAO
    WHERE RANK_PRIORIDADE <= 5
),

APOIADORES AS (
    SELECT
        I.NOME_UF,
        I.ANO,

        I.RANK_MAIOR_CAPACIDADE,
        I.RANK_MENOR_CAPACIDADE,
        I.SCORE_CAPACIDADE,
        I.CENARIO_CAPACIDADE,

        I.RANK_PRESSAO,
        I.SCORE_SOBRECARGA,
        I.CENARIO_SOBRECARGA,

        I.LEITOS_POR_10K_HAB,
        I.UTI_SUS_100K,

        I.PONTO_LEITOS_SOBRECARGA,
        I.PONTO_UTI_SOBRECARGA,

        P.RANK_PRIORIDADE,
        P.SCORE_PRIORIDADE,
        P.NIVEL_PRIORIDADE

    FROM ADMIN.VW_INTELIGENCIA_ASSISTENCIAL I

    JOIN ADMIN.VW_OES_PRIORIZACAO P
      ON P.NOME_UF = I.NOME_UF
     AND P.ANO = I.ANO
),

AVALIACAO AS (
    SELECT
        R.ANO,

        R.NOME_UF AS UF_RECEPTORA,
        R.RANK_PRIORIDADE AS RANK_PRIORIDADE_RECEPTORA,
        R.SCORE_PRIORIDADE AS SCORE_PRIORIDADE_RECEPTORA,
        R.NIVEL_PRIORIDADE AS NIVEL_PRIORIDADE_RECEPTORA,
        R.RANK_PRESSAO AS RANK_PRESSAO_RECEPTORA,

        A.NOME_UF AS UF_APOIADORA,

        A.RANK_MAIOR_CAPACIDADE,
        A.RANK_MENOR_CAPACIDADE,
        A.SCORE_CAPACIDADE,
        A.CENARIO_CAPACIDADE,

        A.RANK_PRESSAO AS RANK_PRESSAO_APOIADORA,
        A.SCORE_SOBRECARGA AS SCORE_SOBRECARGA_APOIADORA,

        A.RANK_PRIORIDADE AS RANK_PRIORIDADE_APOIADORA,
        A.SCORE_PRIORIDADE AS SCORE_PRIORIDADE_APOIADORA,
        A.NIVEL_PRIORIDADE AS NIVEL_PRIORIDADE_APOIADORA,

        A.LEITOS_POR_10K_HAB AS LEITOS_APOIADORA,
        A.UTI_SUS_100K AS UTI_APOIADORA,

        A.PONTO_LEITOS_SOBRECARGA,
        A.PONTO_UTI_SOBRECARGA,

        /* =====================
           COMPONENTES DE RISCO
           ===================== */

        CASE
            WHEN A.RANK_PRESSAO <= 5 THEN 3
            WHEN A.RANK_PRESSAO <= 10 THEN 1
            ELSE 0
        END AS RISCO_PRESSAO,

        CASE
            WHEN A.NIVEL_PRIORIDADE = 'PRIORIDADE_MUITO_ALTA' THEN 3
            WHEN A.NIVEL_PRIORIDADE = 'PRIORIDADE_ALTA' THEN 2
            WHEN A.NIVEL_PRIORIDADE = 'PRIORIDADE_MODERADA' THEN 1
            ELSE 0
        END AS RISCO_PRIORIDADE,

        CASE
            WHEN A.PONTO_UTI_SOBRECARGA = 1 THEN 2
            ELSE 0
        END AS RISCO_UTI,

        CASE
            WHEN A.PONTO_LEITOS_SOBRECARGA = 1 THEN 2
            ELSE 0
        END AS RISCO_LEITOS,

        CASE
            WHEN A.RANK_MAIOR_CAPACIDADE <= 5 THEN 0
            WHEN A.RANK_MAIOR_CAPACIDADE <= 10 THEN 1
            WHEN A.RANK_MAIOR_CAPACIDADE <= 15 THEN 2
            ELSE 3
        END AS RISCO_CAPACIDADE

    FROM RECEPTORES R

    JOIN APOIADORES A
      ON A.ANO = R.ANO
     AND A.NOME_UF <> R.NOME_UF
),

SCORE_RISCO AS (
    SELECT
        A.*,

        (
            RISCO_PRESSAO
          + RISCO_PRIORIDADE
          + RISCO_UTI
          + RISCO_LEITOS
          + RISCO_CAPACIDADE
        ) AS SCORE_RISCO_REALOCACAO

    FROM AVALIACAO A
),

CLASSIFICACAO AS (
    SELECT
        S.*,

        CASE
            WHEN SCORE_RISCO_REALOCACAO >= 6
                THEN 'NAO_RECOMENDADO'

            WHEN SCORE_RISCO_REALOCACAO >= 3
                THEN 'CANDIDATO_COM_RESSALVAS'

            ELSE 'CANDIDATO'
        END AS STATUS_OES

    FROM SCORE_RISCO S
),

RANKING AS (
    SELECT
        C.*,

        ROW_NUMBER() OVER (
            PARTITION BY ANO, UF_RECEPTORA
            ORDER BY
                CASE STATUS_OES
                    WHEN 'CANDIDATO' THEN 1
                    WHEN 'CANDIDATO_COM_RESSALVAS' THEN 2
                    ELSE 3
                END,
                SCORE_RISCO_REALOCACAO ASC,
                RANK_MAIOR_CAPACIDADE ASC,
                RANK_PRESSAO_APOIADORA DESC,
                UF_APOIADORA ASC
        ) AS RANK_APOIO_OES

    FROM CLASSIFICACAO C
)

SELECT
    R."ANO",R."UF_RECEPTORA",R."RANK_PRIORIDADE_RECEPTORA",R."SCORE_PRIORIDADE_RECEPTORA",R."NIVEL_PRIORIDADE_RECEPTORA",R."RANK_PRESSAO_RECEPTORA",R."UF_APOIADORA",R."RANK_MAIOR_CAPACIDADE",R."RANK_MENOR_CAPACIDADE",R."SCORE_CAPACIDADE",R."CENARIO_CAPACIDADE",R."RANK_PRESSAO_APOIADORA",R."SCORE_SOBRECARGA_APOIADORA",R."RANK_PRIORIDADE_APOIADORA",R."SCORE_PRIORIDADE_APOIADORA",R."NIVEL_PRIORIDADE_APOIADORA",R."LEITOS_APOIADORA",R."UTI_APOIADORA",R."PONTO_LEITOS_SOBRECARGA",R."PONTO_UTI_SOBRECARGA",R."RISCO_PRESSAO",R."RISCO_PRIORIDADE",R."RISCO_UTI",R."RISCO_LEITOS",R."RISCO_CAPACIDADE",R."SCORE_RISCO_REALOCACAO",R."STATUS_OES",R."RANK_APOIO_OES",

    CASE
        WHEN STATUS_OES = 'CANDIDATO'
        THEN
            'A UF apresenta boa condição relativa de apoio e baixo risco assistencial pelas regras atuais.'

        WHEN STATUS_OES = 'CANDIDATO_COM_RESSALVAS'
        THEN
            'A UF apresenta potencial de apoio, porém existem sinais de risco que exigem cautela na realocação.'

        ELSE
            'A UF apresenta risco elevado de comprometer sua própria capacidade assistencial caso seja utilizada como apoiadora.'
    END AS JUSTIFICATIVA_OES,

    RTRIM(
          CASE
              WHEN RISCO_PRESSAO >= 3
              THEN 'alta pressão assistencial | '
              WHEN RISCO_PRESSAO = 1
              THEN 'pressão assistencial relevante | '
              ELSE ''
          END

       || CASE
              WHEN RISCO_PRIORIDADE >= 3
              THEN 'prioridade própria muito alta | '
              WHEN RISCO_PRIORIDADE = 2
              THEN 'prioridade própria alta | '
              WHEN RISCO_PRIORIDADE = 1
              THEN 'prioridade própria moderada | '
              ELSE ''
          END

       || CASE
              WHEN RISCO_UTI > 0
              THEN 'fragilidade relativa de UTI | '
              ELSE ''
          END

       || CASE
              WHEN RISCO_LEITOS > 0
              THEN 'fragilidade relativa de leitos | '
              ELSE ''
          END

       || CASE
              WHEN RISCO_CAPACIDADE >= 3
              THEN 'capacidade relativa desfavorável | '
              WHEN RISCO_CAPACIDADE = 2
              THEN 'capacidade relativa intermediária | '
              WHEN RISCO_CAPACIDADE = 1
              THEN 'capacidade relativa moderada | '
              ELSE ''
          END,

        ' |'
    ) AS FATORES_RISCO_REALOCACAO,

    'APO12' AS CONTROLE_COBIT,

    'MITIGACAO_RISCO_REALOCACAO' AS REGRA_OES,

    'VALIDACAO_HUMANA_OBRIGATORIA' AS VALIDACAO_FINAL

FROM RANKING R;


-- ===== VW_PERFIL_ASSISTENCIAL =====
CREATE OR REPLACE FORCE EDITIONABLE VIEW "ADMIN"."VW_PERFIL_ASSISTENCIAL" ("NOME_UF", "ANO", "TOTAL_INTERNACOES", "INTERNACOES_POR_LEITO", "LEITOS_POR_10K_HAB", "MEDIA_PERMANENCIA_ANO", "UTI_SUS_100K", "INDICE_PRESSAO_ASSISTENCIAL", "PERFIL_ASSISTENCIAL") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  WITH BASE AS (
    SELECT
        D.NOME_UF,
        D.ANO,
        D.TOTAL_INTERNACOES,
        D.INTERNACOES_POR_LEITO,
        D.LEITOS_POR_10K_HAB,
        D.MEDIA_PERMANENCIA_ANO,
        I.UTI_SUS_100K
    FROM ADMIN.DATASET_UNIFICADO_UF_2023_2025 D
    LEFT JOIN ADMIN.VW_INDICADORES_TERRITORIAIS I
        ON I.NOME_UF = D.NOME_UF
       AND I.ANO = D.ANO
),
RANKS AS (
    SELECT
        B.*,
        PERCENT_RANK() OVER (
            PARTITION BY ANO
            ORDER BY TOTAL_INTERNACOES
        ) AS R_DEMANDA,
        PERCENT_RANK() OVER (
            PARTITION BY ANO
            ORDER BY INTERNACOES_POR_LEITO
        ) AS R_PRESSAO,
        PERCENT_RANK() OVER (
            PARTITION BY ANO
            ORDER BY MEDIA_PERMANENCIA_ANO
        ) AS R_PERMANENCIA,
        PERCENT_RANK() OVER (
            PARTITION BY ANO
            ORDER BY LEITOS_POR_10K_HAB
        ) AS R_CAPACIDADE,
        PERCENT_RANK() OVER (
            PARTITION BY ANO
            ORDER BY UTI_SUS_100K
        ) AS R_UTI
    FROM BASE B
),
SCORES AS (
    SELECT
        R.*,
        (
            0.35 * R_PRESSAO
          + 0.30 * R_DEMANDA
          + 0.20 * R_PERMANENCIA
          - 0.20 * R_CAPACIDADE
          - 0.15 * R_UTI
        ) AS SCORE_BRUTO
    FROM RANKS R
),
ESCALA AS (
    SELECT
        S.*,
        MIN(SCORE_BRUTO) OVER (
            PARTITION BY ANO
        ) AS MIN_SCORE,
        MAX(SCORE_BRUTO) OVER (
            PARTITION BY ANO
        ) AS MAX_SCORE
    FROM SCORES S
)
SELECT
    NOME_UF,
    ANO,
    TOTAL_INTERNACOES,
    INTERNACOES_POR_LEITO,
    LEITOS_POR_10K_HAB,
    MEDIA_PERMANENCIA_ANO,
    UTI_SUS_100K,
    ROUND(
        CASE
            WHEN MAX_SCORE = MIN_SCORE THEN 50
            ELSE (
                (SCORE_BRUTO - MIN_SCORE)
                / NULLIF(MAX_SCORE - MIN_SCORE, 0)
            ) * 100
        END,
        2
    ) AS INDICE_PRESSAO_ASSISTENCIAL,
    CASE
        WHEN MAX_SCORE = MIN_SCORE
            THEN 'Pressão Assistencial Intermediária'
        WHEN (
            (SCORE_BRUTO - MIN_SCORE)
            / NULLIF(MAX_SCORE - MIN_SCORE, 0)
        ) * 100 < 33.3333
            THEN 'Baixa Pressão Assistencial'
        WHEN (
            (SCORE_BRUTO - MIN_SCORE)
            / NULLIF(MAX_SCORE - MIN_SCORE, 0)
        ) * 100 < 66.6667
            THEN 'Pressão Assistencial Intermediária'
        ELSE 'Alta Pressão Assistencial'
    END AS PERFIL_ASSISTENCIAL
FROM ESCALA;


-- ===== VW_PERFIL_ASSISTENCIAL_V2 =====
CREATE OR REPLACE FORCE EDITIONABLE VIEW "ADMIN"."VW_PERFIL_ASSISTENCIAL_V2" ("NOME_UF", "ANO", "TOTAL_INTERNACOES", "INTERNACOES_POR_LEITO", "LEITOS_POR_10K_HAB", "MEDIA_PERMANENCIA_ANO", "LEITOS_UTI_TOTAL", "INDICE_PRESSAO_ASSISTENCIAL", "PERFIL_ASSISTENCIAL") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  WITH BASE AS (
    SELECT
        NOME_UF,
        ANO,
        TOTAL_INTERNACOES,
        INTERNACOES_POR_LEITO,
        LEITOS_POR_10K_HAB,
        MEDIA_PERMANENCIA_ANO,
        LEITOS_UTI_TOTAL
    FROM ADMIN.DATASET_UNIFICADO_UF_2023_2025
),
RANKS AS (
    SELECT
        BASE.*,

        PERCENT_RANK() OVER (
            PARTITION BY ANO
            ORDER BY TOTAL_INTERNACOES
        ) AS R_DEMANDA,

        PERCENT_RANK() OVER (
            PARTITION BY ANO
            ORDER BY INTERNACOES_POR_LEITO
        ) AS R_PRESSAO,

        PERCENT_RANK() OVER (
            PARTITION BY ANO
            ORDER BY MEDIA_PERMANENCIA_ANO
        ) AS R_PERMANENCIA,

        PERCENT_RANK() OVER (
            PARTITION BY ANO
            ORDER BY LEITOS_POR_10K_HAB
        ) AS R_CAPACIDADE,

        PERCENT_RANK() OVER (
            PARTITION BY ANO
            ORDER BY LEITOS_UTI_TOTAL
        ) AS R_UTI

    FROM BASE
),
SCORES AS (
    SELECT
        RANKS.*,

        (
            0.35 * R_PRESSAO
            + 0.30 * R_DEMANDA
            + 0.20 * R_PERMANENCIA
            - 0.20 * R_CAPACIDADE
            - 0.15 * R_UTI
        ) AS SCORE_BRUTO

    FROM RANKS
),
ESCALA AS (
    SELECT
        SCORES.*,

        MIN(SCORE_BRUTO) OVER (
            PARTITION BY ANO
        ) AS MIN_SCORE,

        MAX(SCORE_BRUTO) OVER (
            PARTITION BY ANO
        ) AS MAX_SCORE

    FROM SCORES
)
SELECT
    NOME_UF,
    ANO,
    TOTAL_INTERNACOES,
    INTERNACOES_POR_LEITO,
    LEITOS_POR_10K_HAB,
    MEDIA_PERMANENCIA_ANO,
    LEITOS_UTI_TOTAL,

    ROUND(
        CASE
            WHEN MAX_SCORE = MIN_SCORE THEN 50
            ELSE (
                (SCORE_BRUTO - MIN_SCORE)
                / NULLIF(MAX_SCORE - MIN_SCORE, 0)
            ) * 100
        END,
        2
    ) AS INDICE_PRESSAO_ASSISTENCIAL,

    CASE
        WHEN MAX_SCORE = MIN_SCORE THEN
            'Pressão Assistencial Intermediária'

        WHEN (
            (SCORE_BRUTO - MIN_SCORE)
            / NULLIF(MAX_SCORE - MIN_SCORE, 0)
        ) * 100 < 33.3333 THEN
            'Baixa Pressão Assistencial'

        WHEN (
            (SCORE_BRUTO - MIN_SCORE)
            / NULLIF(MAX_SCORE - MIN_SCORE, 0)
        ) * 100 < 66.6667 THEN
            'Pressão Assistencial Intermediária'

        ELSE
            'Alta Pressão Assistencial'
    END AS PERFIL_ASSISTENCIAL

FROM ESCALA;


-- ===== VW_PERFIL_ASSISTENCIAL_V3 =====
CREATE OR REPLACE FORCE EDITIONABLE VIEW "ADMIN"."VW_PERFIL_ASSISTENCIAL_V3" ("NOME_UF", "ANO", "TOTAL_INTERNACOES", "INTERNACOES_POR_LEITO", "LEITOS_POR_10K_HAB", "MEDIA_PERMANENCIA_ANO", "UTI_SUS_100K", "INDICE_PRESSAO_ASSISTENCIAL", "PERFIL_ASSISTENCIAL") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  WITH BASE AS (
    SELECT
        D.NOME_UF,
        D.ANO,
        D.TOTAL_INTERNACOES,
        D.INTERNACOES_POR_LEITO,
        D.LEITOS_POR_10K_HAB,
        D.MEDIA_PERMANENCIA_ANO,
        I.UTI_SUS_100K
    FROM ADMIN.DATASET_UNIFICADO_UF_2023_2025 D
    LEFT JOIN ADMIN.VW_INDICADORES_TERRITORIAIS I
        ON I.NOME_UF = D.NOME_UF
       AND I.ANO = D.ANO
),
RANKS AS (
    SELECT
        B.*,
        PERCENT_RANK() OVER (
            PARTITION BY ANO
            ORDER BY TOTAL_INTERNACOES
        ) AS R_DEMANDA,
        PERCENT_RANK() OVER (
            PARTITION BY ANO
            ORDER BY INTERNACOES_POR_LEITO
        ) AS R_PRESSAO,
        PERCENT_RANK() OVER (
            PARTITION BY ANO
            ORDER BY MEDIA_PERMANENCIA_ANO
        ) AS R_PERMANENCIA,
        PERCENT_RANK() OVER (
            PARTITION BY ANO
            ORDER BY LEITOS_POR_10K_HAB
        ) AS R_CAPACIDADE,
        PERCENT_RANK() OVER (
            PARTITION BY ANO
            ORDER BY UTI_SUS_100K
        ) AS R_UTI
    FROM BASE B
),
SCORES AS (
    SELECT
        R.*,
        (
            0.35 * R_PRESSAO
          + 0.30 * R_DEMANDA
          + 0.20 * R_PERMANENCIA
          - 0.20 * R_CAPACIDADE
          - 0.15 * R_UTI
        ) AS SCORE_BRUTO
    FROM RANKS R
),
ESCALA AS (
    SELECT
        S.*,
        MIN(SCORE_BRUTO) OVER (
            PARTITION BY ANO
        ) AS MIN_SCORE,
        MAX(SCORE_BRUTO) OVER (
            PARTITION BY ANO
        ) AS MAX_SCORE
    FROM SCORES S
)
SELECT
    NOME_UF,
    ANO,
    TOTAL_INTERNACOES,
    INTERNACOES_POR_LEITO,
    LEITOS_POR_10K_HAB,
    MEDIA_PERMANENCIA_ANO,
    UTI_SUS_100K,
    ROUND(
        CASE
            WHEN MAX_SCORE = MIN_SCORE THEN 50
            ELSE (
                (SCORE_BRUTO - MIN_SCORE)
                / NULLIF(MAX_SCORE - MIN_SCORE, 0)
            ) * 100
        END,
        2
    ) AS INDICE_PRESSAO_ASSISTENCIAL,
    CASE
        WHEN MAX_SCORE = MIN_SCORE
            THEN 'Pressão Assistencial Intermediária'
        WHEN (
            (SCORE_BRUTO - MIN_SCORE)
            / NULLIF(MAX_SCORE - MIN_SCORE, 0)
        ) * 100 < 33.3333
            THEN 'Baixa Pressão Assistencial'
        WHEN (
            (SCORE_BRUTO - MIN_SCORE)
            / NULLIF(MAX_SCORE - MIN_SCORE, 0)
        ) * 100 < 66.6667
            THEN 'Pressão Assistencial Intermediária'
        ELSE 'Alta Pressão Assistencial'
    END AS PERFIL_ASSISTENCIAL
FROM ESCALA;


-- ===== VW_PERFIL_ATENDIMENTO =====
CREATE OR REPLACE FORCE EDITIONABLE VIEW "ADMIN"."VW_PERFIL_ATENDIMENTO" ("NOME_UF", "ANO", "TIPO_UNIDADE_PREDOMINANTE", "PORTE_PREDOMINANTE", "QTD_ESTABELECIMENTOS", "LEITOS_EXISTENTES", "LEITOS_SUS_CNES", "UTI_TOTAL_EXIST", "UTI_TOTAL_SUS", "TOTAL_INTERNACOES", "INTERNACOES_POR_LEITO", "LEITOS_POR_10K_HAB", "UTI_SUS_100K", "INDICE_PRESSAO_ASSISTENCIAL", "PERFIL_ASSISTENCIAL", "TAXA_MORTALIDADE_HOSPITALAR", "GASTO_MEDIO_INTERNACAO") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  WITH TIPO_PREDOMINANTE AS (
    SELECT
        NOME_UF,
        ANO_REF,
        DS_TIPO_UNIDADE,
        COUNT(DISTINCT CNES) AS QTD,
        ROW_NUMBER() OVER (
            PARTITION BY NOME_UF, ANO_REF
            ORDER BY COUNT(DISTINCT CNES) DESC,
                     DS_TIPO_UNIDADE
        ) AS RN
    FROM ADMIN.CNES_LEITOS_2023_2025
    WHERE COMP = ADD_MONTHS(
        TO_DATE(ANO_REF || '-01-01', 'YYYY-MM-DD'),
        11
    )
    GROUP BY
        NOME_UF,
        ANO_REF,
        DS_TIPO_UNIDADE
),

PORTE_PREDOMINANTE AS (
    SELECT
        NOME_UF,
        ANO_REF,
        PORTE,
        COUNT(DISTINCT CNES) AS QTD,
        ROW_NUMBER() OVER (
            PARTITION BY NOME_UF, ANO_REF
            ORDER BY COUNT(DISTINCT CNES) DESC,
                     PORTE
        ) AS RN
    FROM ADMIN.CNES_LEITOS_2023_2025
    WHERE COMP = ADD_MONTHS(
        TO_DATE(ANO_REF || '-01-01', 'YYYY-MM-DD'),
        11
    )
    GROUP BY
        NOME_UF,
        ANO_REF,
        PORTE
)

SELECT
    P.NOME_UF,
    P.ANO,

    /* ESTRUTURA CNES */
    T.DS_TIPO_UNIDADE AS TIPO_UNIDADE_PREDOMINANTE,
    PO.PORTE AS PORTE_PREDOMINANTE,

    /* CAPACIDADE */
    I.QTD_ESTABELECIMENTOS,
    I.LEITOS_EXISTENTES,
    I.LEITOS_SUS_CNES,
    I.UTI_TOTAL_EXIST,
    I.UTI_TOTAL_SUS,

    /* DEMANDA */
    P.TOTAL_INTERNACOES,
    P.INTERNACOES_POR_LEITO,

    /* OFERTA RELATIVA */
    P.LEITOS_POR_10K_HAB,
    I.UTI_SUS_100K,

    /* PRESSÃO */
    P.INDICE_PRESSAO_ASSISTENCIAL,
    P.PERFIL_ASSISTENCIAL,

    /* COMPLEMENTARES */
    I.TAXA_MORTALIDADE_HOSPITALAR,
    I.GASTO_MEDIO_INTERNACAO

FROM ADMIN.VW_PERFIL_ASSISTENCIAL P

JOIN ADMIN.VW_INDICADORES_TERRITORIAIS I
    ON UPPER(TRIM(I.NOME_UF)) = UPPER(TRIM(P.NOME_UF))
   AND I.ANO = P.ANO

LEFT JOIN TIPO_PREDOMINANTE T
    ON UPPER(TRIM(T.NOME_UF)) = UPPER(TRIM(P.NOME_UF))
   AND T.ANO_REF = P.ANO
   AND T.RN = 1

LEFT JOIN PORTE_PREDOMINANTE PO
    ON UPPER(TRIM(PO.NOME_UF)) = UPPER(TRIM(P.NOME_UF))
   AND PO.ANO_REF = P.ANO
   AND PO.RN = 1;


-- ===== VW_PERFIL_HOSPITAL =====
CREATE OR REPLACE FORCE EDITIONABLE VIEW "ADMIN"."VW_PERFIL_HOSPITAL" ("ANO", "NOME_UF", "CO_UF_IBGE", "UF", "MUNICIPIO", "CNES", "NOME_ESTABELECIMENTO", "TP_GESTAO", "TIPO_UNIDADE", "NATUREZA_JURIDICA", "PORTE", "LEITOS_EXISTENTES", "LEITOS_SUS", "UTI_TOTAL_EXIST", "UTI_TOTAL_SUS", "UTI_ADULTO_EXIST", "UTI_ADULTO_SUS", "UTI_PEDIATRICO_EXIST", "UTI_PEDIATRICO_SUS", "UTI_NEONATAL_EXIST", "UTI_NEONATAL_SUS", "UTI_QUEIMADO_EXIST", "UTI_QUEIMADO_SUS", "UTI_CORONARIANA_EXIST", "UTI_CORONARIANA_SUS") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  SELECT
    C."ANO_REF" AS "ANO",
    C."NOME_UF",
    C."CO_IBGE" AS "CO_UF_IBGE",
    C."UF",
    C."MUNICIPIO",
    C."CNES",
    C."NOME_ESTABELECIMENTO",
    C."TP_GESTAO",
    C."DS_TIPO_UNIDADE" AS "TIPO_UNIDADE",
    C."DESC_NATUREZA_JURIDICA" AS "NATUREZA_JURIDICA",
    C."PORTE",

    C."LEITOS_EXISTENTES",
    C."LEITOS_SUS",

    C."UTI_TOTAL_EXIST",
    C."UTI_TOTAL_SUS",

    C."UTI_ADULTO_EXIST",
    C."UTI_ADULTO_SUS",

    C."UTI_PEDIATRICO_EXIST",
    C."UTI_PEDIATRICO_SUS",

    C."UTI_NEONATAL_EXIST",
    C."UTI_NEONATAL_SUS",

    C."UTI_QUEIMADO_EXIST",
    C."UTI_QUEIMADO_SUS",

    C."UTI_CORONARIANA_EXIST",
    C."UTI_CORONARIANA_SUS"

FROM ADMIN."CNES_LEITOS_2023_2025" C;


-- ===== VW_PERFIL_HOSPITAL_ATUAL =====
CREATE OR REPLACE FORCE EDITIONABLE VIEW "ADMIN"."VW_PERFIL_HOSPITAL_ATUAL" ("ANO", "NOME_UF", "CO_UF_IBGE", "UF", "MUNICIPIO", "CNES", "NOME_ESTABELECIMENTO", "TP_GESTAO", "TIPO_UNIDADE", "NATUREZA_JURIDICA", "PORTE", "LEITOS_EXISTENTES", "LEITOS_SUS", "UTI_TOTAL_EXIST", "UTI_TOTAL_SUS", "UTI_ADULTO_EXIST", "UTI_ADULTO_SUS", "UTI_PEDIATRICO_EXIST", "UTI_PEDIATRICO_SUS", "UTI_NEONATAL_EXIST", "UTI_NEONATAL_SUS", "UTI_QUEIMADO_EXIST", "UTI_QUEIMADO_SUS", "UTI_CORONARIANA_EXIST", "UTI_CORONARIANA_SUS") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  SELECT
    ANO,
    NOME_UF,
    CO_UF_IBGE,
    UF,
    MUNICIPIO,
    CNES,
    NOME_ESTABELECIMENTO,
    TP_GESTAO,
    TIPO_UNIDADE,
    NATUREZA_JURIDICA,
    PORTE,
    LEITOS_EXISTENTES,
    LEITOS_SUS,
    UTI_TOTAL_EXIST,
    UTI_TOTAL_SUS,
    UTI_ADULTO_EXIST,
    UTI_ADULTO_SUS,
    UTI_PEDIATRICO_EXIST,
    UTI_PEDIATRICO_SUS,
    UTI_NEONATAL_EXIST,
    UTI_NEONATAL_SUS,
    UTI_QUEIMADO_EXIST,
    UTI_QUEIMADO_SUS,
    UTI_CORONARIANA_EXIST,
    UTI_CORONARIANA_SUS
FROM (
    SELECT
        H.*,
        ROW_NUMBER() OVER (
            PARTITION BY CNES
            ORDER BY ANO DESC
        ) AS RN
    FROM ADMIN.VW_PERFIL_HOSPITAL H
    WHERE CNES IS NOT NULL
)
WHERE RN = 1;


-- ===== VW_SIMULACAO_SOBRECARGA =====
CREATE OR REPLACE FORCE EDITIONABLE VIEW "ADMIN"."VW_SIMULACAO_SOBRECARGA" ("NOME_UF", "ANO", "PERFIL_ASSISTENCIAL", "INDICE_PRESSAO_ASSISTENCIAL", "TOTAL_INTERNACOES", "INTERNACOES_POR_LEITO", "LEITOS_POR_10K_HAB", "UTI_SUS_100K", "MEDIANA_PRESSAO", "MEDIANA_DEMANDA", "MEDIANA_LEITOS", "MEDIANA_UTI", "PONTO_PRESSAO", "PONTO_DEMANDA", "PONTO_LEITOS", "PONTO_UTI", "SCORE_SOBRECARGA", "CENARIO_SOBRECARGA", "RANK_PRESSAO", "RANK_CAPACIDADE", "VARIACAO_PRESSAO_ANUAL", "VARIACAO_PRESSAO_PERIODO") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  WITH BASE AS (
    SELECT
        P.NOME_UF,
        P.ANO,
        P.PERFIL_ASSISTENCIAL,
        P.INDICE_PRESSAO_ASSISTENCIAL,
        P.TOTAL_INTERNACOES,
        P.INTERNACOES_POR_LEITO,
        P.LEITOS_POR_10K_HAB,
        P.UTI_SUS_100K
    FROM ADMIN.VW_PERFIL_ASSISTENCIAL P
),
REFERENCIAS AS (
    SELECT
        B.*,

        MEDIAN(INDICE_PRESSAO_ASSISTENCIAL) OVER (
            PARTITION BY ANO
        ) AS MEDIANA_PRESSAO,

        MEDIAN(INTERNACOES_POR_LEITO) OVER (
            PARTITION BY ANO
        ) AS MEDIANA_DEMANDA,

        MEDIAN(LEITOS_POR_10K_HAB) OVER (
            PARTITION BY ANO
        ) AS MEDIANA_LEITOS,

        MEDIAN(UTI_SUS_100K) OVER (
            PARTITION BY ANO
        ) AS MEDIANA_UTI,

        ROW_NUMBER() OVER (
            PARTITION BY ANO
            ORDER BY
                INDICE_PRESSAO_ASSISTENCIAL DESC,
                INTERNACOES_POR_LEITO DESC,
                NOME_UF
        ) AS RANK_PRESSAO,

        ROW_NUMBER() OVER (
            PARTITION BY ANO
            ORDER BY
                LEITOS_POR_10K_HAB DESC,
                UTI_SUS_100K DESC,
                NOME_UF
        ) AS RANK_CAPACIDADE

    FROM BASE B
),
PONTOS AS (
    SELECT
        R.*,

        CASE
            WHEN INDICE_PRESSAO_ASSISTENCIAL > MEDIANA_PRESSAO
            THEN 1
            ELSE 0
        END AS PONTO_PRESSAO,

        CASE
            WHEN INTERNACOES_POR_LEITO > MEDIANA_DEMANDA
            THEN 1
            ELSE 0
        END AS PONTO_DEMANDA,

        CASE
            WHEN LEITOS_POR_10K_HAB < MEDIANA_LEITOS
            THEN 1
            ELSE 0
        END AS PONTO_LEITOS,

        CASE
            WHEN UTI_SUS_100K < MEDIANA_UTI
            THEN 1
            ELSE 0
        END AS PONTO_UTI

    FROM REFERENCIAS R
),
SCORES AS (
    SELECT
        P.*,

        (
            PONTO_PRESSAO
          + PONTO_DEMANDA
          + PONTO_LEITOS
          + PONTO_UTI
        ) AS SCORE_SOBRECARGA

    FROM PONTOS P
),
HISTORICO AS (
    SELECT
        S.*,

        LAG(INDICE_PRESSAO_ASSISTENCIAL) OVER (
            PARTITION BY NOME_UF
            ORDER BY ANO
        ) AS PRESSAO_ANO_ANTERIOR,

        FIRST_VALUE(INDICE_PRESSAO_ASSISTENCIAL) OVER (
            PARTITION BY NOME_UF
            ORDER BY ANO
            ROWS BETWEEN UNBOUNDED PRECEDING
                     AND UNBOUNDED FOLLOWING
        ) AS PRESSAO_INICIAL

    FROM SCORES S
)
SELECT
    NOME_UF,
    ANO,
    PERFIL_ASSISTENCIAL,

    ROUND(
        INDICE_PRESSAO_ASSISTENCIAL,
        2
    ) AS INDICE_PRESSAO_ASSISTENCIAL,

    TOTAL_INTERNACOES,

    ROUND(
        INTERNACOES_POR_LEITO,
        2
    ) AS INTERNACOES_POR_LEITO,

    ROUND(
        LEITOS_POR_10K_HAB,
        2
    ) AS LEITOS_POR_10K_HAB,

    ROUND(
        UTI_SUS_100K,
        2
    ) AS UTI_SUS_100K,

    ROUND(
        MEDIANA_PRESSAO,
        2
    ) AS MEDIANA_PRESSAO,

    ROUND(
        MEDIANA_DEMANDA,
        2
    ) AS MEDIANA_DEMANDA,

    ROUND(
        MEDIANA_LEITOS,
        2
    ) AS MEDIANA_LEITOS,

    ROUND(
        MEDIANA_UTI,
        2
    ) AS MEDIANA_UTI,

    PONTO_PRESSAO,
    PONTO_DEMANDA,
    PONTO_LEITOS,
    PONTO_UTI,

    SCORE_SOBRECARGA,

    CASE
        WHEN SCORE_SOBRECARGA <= 1
            THEN 'SEM SINAL RELEVANTE'

        WHEN SCORE_SOBRECARGA = 2
            THEN 'ATENCAO'

        WHEN SCORE_SOBRECARGA = 3
            THEN 'SOBRECARGA PROVAVEL'

        ELSE
            'SOBRECARGA CRITICA'
    END AS CENARIO_SOBRECARGA,

    RANK_PRESSAO,
    RANK_CAPACIDADE,

    ROUND(
        INDICE_PRESSAO_ASSISTENCIAL
        - PRESSAO_ANO_ANTERIOR,
        2
    ) AS VARIACAO_PRESSAO_ANUAL,

    ROUND(
        INDICE_PRESSAO_ASSISTENCIAL
        - PRESSAO_INICIAL,
        2
    ) AS VARIACAO_PRESSAO_PERIODO

FROM HISTORICO;


-- ===== VW_SIMULACAO_SOBRECARGA_V2 =====
CREATE OR REPLACE FORCE EDITIONABLE VIEW "ADMIN"."VW_SIMULACAO_SOBRECARGA_V2" ("NOME_UF", "ANO", "PERFIL_ASSISTENCIAL", "INDICE_PRESSAO_ASSISTENCIAL", "TOTAL_INTERNACOES", "INTERNACOES_POR_LEITO", "LEITOS_POR_10K_HAB", "UTI_SUS_100K", "MEDIANA_PRESSAO", "MEDIANA_DEMANDA", "MEDIANA_LEITOS", "MEDIANA_UTI", "PONTO_PRESSAO", "PONTO_DEMANDA", "PONTO_LEITOS", "PONTO_UTI", "SCORE_SOBRECARGA", "CENARIO_SOBRECARGA", "RANK_PRESSAO", "RANK_CAPACIDADE", "VARIACAO_PRESSAO_ANUAL", "VARIACAO_PRESSAO_PERIODO") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  WITH BASE AS (
    SELECT
        P.NOME_UF,
        P.ANO,
        P.PERFIL_ASSISTENCIAL,
        P.INDICE_PRESSAO_ASSISTENCIAL,
        P.TOTAL_INTERNACOES,
        P.INTERNACOES_POR_LEITO,
        P.LEITOS_POR_10K_HAB,
        P.UTI_SUS_100K
    FROM ADMIN.VW_PERFIL_ASSISTENCIAL P
),
REFERENCIAS AS (
    SELECT
        B.*,

        MEDIAN(INDICE_PRESSAO_ASSISTENCIAL) OVER (
            PARTITION BY ANO
        ) AS MEDIANA_PRESSAO,

        MEDIAN(INTERNACOES_POR_LEITO) OVER (
            PARTITION BY ANO
        ) AS MEDIANA_DEMANDA,

        MEDIAN(LEITOS_POR_10K_HAB) OVER (
            PARTITION BY ANO
        ) AS MEDIANA_LEITOS,

        MEDIAN(UTI_SUS_100K) OVER (
            PARTITION BY ANO
        ) AS MEDIANA_UTI,

ROW_NUMBER() OVER (
    PARTITION BY ANO
    ORDER BY
        INDICE_PRESSAO_ASSISTENCIAL DESC,
        INTERNACOES_POR_LEITO DESC,
        NOME_UF
) AS RANK_PRESSAO,

ROW_NUMBER() OVER (
    PARTITION BY ANO
    ORDER BY
        LEITOS_POR_10K_HAB DESC,
        UTI_SUS_100K DESC,
        NOME_UF
) AS RANK_CAPACIDADE

    FROM BASE B
),
PONTOS AS (
    SELECT
        R.*,

        CASE
            WHEN INDICE_PRESSAO_ASSISTENCIAL > MEDIANA_PRESSAO
            THEN 1 ELSE 0
        END AS PONTO_PRESSAO,

        CASE
            WHEN INTERNACOES_POR_LEITO > MEDIANA_DEMANDA
            THEN 1 ELSE 0
        END AS PONTO_DEMANDA,

        CASE
            WHEN LEITOS_POR_10K_HAB < MEDIANA_LEITOS
            THEN 1 ELSE 0
        END AS PONTO_LEITOS,

        CASE
            WHEN UTI_SUS_100K < MEDIANA_UTI
            THEN 1 ELSE 0
        END AS PONTO_UTI

    FROM REFERENCIAS R
),
SCORES AS (
    SELECT
        P.*,

        (
            PONTO_PRESSAO
          + PONTO_DEMANDA
          + PONTO_LEITOS
          + PONTO_UTI
        ) AS SCORE_SOBRECARGA

    FROM PONTOS P
),
HISTORICO AS (
    SELECT
        S.*,

        LAG(INDICE_PRESSAO_ASSISTENCIAL) OVER (
            PARTITION BY NOME_UF
            ORDER BY ANO
        ) AS PRESSAO_ANO_ANTERIOR,

        FIRST_VALUE(INDICE_PRESSAO_ASSISTENCIAL) OVER (
            PARTITION BY NOME_UF
            ORDER BY ANO
            ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING
        ) AS PRESSAO_INICIAL

    FROM SCORES S
)
SELECT
    NOME_UF,
    ANO,
    PERFIL_ASSISTENCIAL,

    ROUND(INDICE_PRESSAO_ASSISTENCIAL, 2) AS INDICE_PRESSAO_ASSISTENCIAL,
    TOTAL_INTERNACOES,
    ROUND(INTERNACOES_POR_LEITO, 2) AS INTERNACOES_POR_LEITO,
    ROUND(LEITOS_POR_10K_HAB, 2) AS LEITOS_POR_10K_HAB,
    ROUND(UTI_SUS_100K, 2) AS UTI_SUS_100K,

    ROUND(MEDIANA_PRESSAO, 2) AS MEDIANA_PRESSAO,
    ROUND(MEDIANA_DEMANDA, 2) AS MEDIANA_DEMANDA,
    ROUND(MEDIANA_LEITOS, 2) AS MEDIANA_LEITOS,
    ROUND(MEDIANA_UTI, 2) AS MEDIANA_UTI,

    PONTO_PRESSAO,
    PONTO_DEMANDA,
    PONTO_LEITOS,
    PONTO_UTI,

    SCORE_SOBRECARGA,

    CASE
        WHEN SCORE_SOBRECARGA <= 1
            THEN 'SEM SINAL RELEVANTE'
        WHEN SCORE_SOBRECARGA = 2
            THEN 'ATENCAO'
        WHEN SCORE_SOBRECARGA = 3
            THEN 'SOBRECARGA PROVAVEL'
        ELSE
            'SOBRECARGA CRITICA'
    END AS CENARIO_SOBRECARGA,

    RANK_PRESSAO,
    RANK_CAPACIDADE,

    ROUND(
        INDICE_PRESSAO_ASSISTENCIAL - PRESSAO_ANO_ANTERIOR,
        2
    ) AS VARIACAO_PRESSAO_ANUAL,

    ROUND(
        INDICE_PRESSAO_ASSISTENCIAL - PRESSAO_INICIAL,
        2
    ) AS VARIACAO_PRESSAO_PERIODO

FROM HISTORICO;


-- ===== VW_SIMULACAO_SUBUTILIZACAO =====
CREATE OR REPLACE FORCE EDITIONABLE VIEW "ADMIN"."VW_SIMULACAO_SUBUTILIZACAO" ("NOME_UF", "ANO", "PERFIL_ASSISTENCIAL", "INDICE_PRESSAO_ASSISTENCIAL", "TOTAL_INTERNACOES", "LEITOS_SUS_CNES", "LEITOS_POR_10K_HAB", "UTI_SUS_100K", "INTERNACOES_POR_LEITO", "PONTO_PRESSAO", "PONTO_DEMANDA", "PONTO_LEITOS", "PONTO_UTI", "SCORE_SUBUTILIZACAO", "SCORE_CAPACIDADE", "CENARIO_SUBUTILIZACAO", "RANK_MAIOR_CAPACIDADE", "RANK_MENOR_CAPACIDADE") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  WITH BASE AS (
    SELECT
        NOME_UF,
        ANO,
        PERFIL_ASSISTENCIAL,
        INDICE_PRESSAO_ASSISTENCIAL,
        TOTAL_INTERNACOES,
        LEITOS_SUS_CNES,
        LEITOS_POR_10K_HAB,
        UTI_SUS_100K,
        INTERNACOES_POR_LEITO
    FROM ADMIN.VW_PERFIL_ATENDIMENTO
),

LIMITES AS (
    SELECT
        ANO,

        PERCENTILE_CONT(0.50)
            WITHIN GROUP (
                ORDER BY INDICE_PRESSAO_ASSISTENCIAL
            ) AS MED_PRESSAO,

        PERCENTILE_CONT(0.50)
            WITHIN GROUP (
                ORDER BY INTERNACOES_POR_LEITO
            ) AS MED_DEMANDA_LEITO,

        PERCENTILE_CONT(0.50)
            WITHIN GROUP (
                ORDER BY LEITOS_POR_10K_HAB
            ) AS MED_LEITOS_10K,

        PERCENTILE_CONT(0.50)
            WITHIN GROUP (
                ORDER BY UTI_SUS_100K
            ) AS MED_UTI_100K

    FROM BASE
    GROUP BY ANO
),

PONTOS AS (
    SELECT
        B.NOME_UF,
        B.ANO,
        B.PERFIL_ASSISTENCIAL,
        B.INDICE_PRESSAO_ASSISTENCIAL,
        B.TOTAL_INTERNACOES,
        B.LEITOS_SUS_CNES,
        B.LEITOS_POR_10K_HAB,
        B.UTI_SUS_100K,
        B.INTERNACOES_POR_LEITO,

        CASE
            WHEN B.INDICE_PRESSAO_ASSISTENCIAL < L.MED_PRESSAO
            THEN 1
            ELSE 0
        END AS PONTO_PRESSAO,

        CASE
            WHEN B.INTERNACOES_POR_LEITO < L.MED_DEMANDA_LEITO
            THEN 1
            ELSE 0
        END AS PONTO_DEMANDA,

        CASE
            WHEN B.LEITOS_POR_10K_HAB > L.MED_LEITOS_10K
            THEN 1
            ELSE 0
        END AS PONTO_LEITOS,

        CASE
            WHEN B.UTI_SUS_100K > L.MED_UTI_100K
            THEN 1
            ELSE 0
        END AS PONTO_UTI

    FROM BASE B

    INNER JOIN LIMITES L
        ON L.ANO = B.ANO
),

SCORES AS (
    SELECT
        P.*,

        (
            P.PONTO_PRESSAO
            + P.PONTO_DEMANDA
            + P.PONTO_LEITOS
            + P.PONTO_UTI
        ) AS SCORE_SUBUTILIZACAO

    FROM PONTOS P
),

CLASSIFICACAO AS (
    SELECT
        S.*,

        /*
        Nome amigável utilizado pelo dashboard / Select AI.

        É o mesmo score analítico da oportunidade de capacidade,
        variando de 0 a 4.

        Não representa percentual de capacidade.
        */
        S.SCORE_SUBUTILIZACAO AS SCORE_CAPACIDADE,

        CASE
            WHEN S.SCORE_SUBUTILIZACAO = 4
                THEN 'SUBUTILIZACAO ELEVADA'

            WHEN S.SCORE_SUBUTILIZACAO = 3
                THEN 'SUBUTILIZACAO PROVAVEL'

            WHEN S.SCORE_SUBUTILIZACAO = 2
                THEN 'ATENCAO'

            ELSE 'SEM SINAL RELEVANTE'
        END AS CENARIO_SUBUTILIZACAO

    FROM SCORES S
)

SELECT
    C.NOME_UF,
    C.ANO,
    C.PERFIL_ASSISTENCIAL,
    C.INDICE_PRESSAO_ASSISTENCIAL,
    C.TOTAL_INTERNACOES,
    C.LEITOS_SUS_CNES,
    C.LEITOS_POR_10K_HAB,
    C.UTI_SUS_100K,
    C.INTERNACOES_POR_LEITO,

    C.PONTO_PRESSAO,
    C.PONTO_DEMANDA,
    C.PONTO_LEITOS,
    C.PONTO_UTI,

    C.SCORE_SUBUTILIZACAO,
    C.SCORE_CAPACIDADE,
    C.CENARIO_SUBUTILIZACAO,

    /*
    1 = maior oportunidade/capacidade relativa no ano.

    Critério:
    1. Score maior
    2. Mais leitos por 10 mil
    3. Mais UTI por 100 mil
    */
    ROW_NUMBER() OVER (
        PARTITION BY C.ANO
        ORDER BY
            C.SCORE_CAPACIDADE DESC,
            C.LEITOS_POR_10K_HAB DESC,
            C.UTI_SUS_100K DESC,
            C.NOME_UF ASC
    ) AS RANK_MAIOR_CAPACIDADE,

    /*
    1 = menor oportunidade/capacidade relativa no ano.

    Critério:
    1. Score menor
    2. Menos leitos por 10 mil
    3. Menos UTI por 100 mil
    */
    ROW_NUMBER() OVER (
        PARTITION BY C.ANO
        ORDER BY
            C.SCORE_CAPACIDADE ASC,
            C.LEITOS_POR_10K_HAB ASC,
            C.UTI_SUS_100K ASC,
            C.NOME_UF ASC
    ) AS RANK_MENOR_CAPACIDADE

FROM CLASSIFICACAO C;


-- ===== VW_TRANSICAO_PERFIL_ASSISTENCIAL =====
CREATE OR REPLACE FORCE EDITIONABLE VIEW "ADMIN"."VW_TRANSICAO_PERFIL_ASSISTENCIAL" ("NOME_UF", "PERFIL_2023", "PERFIL_2025", "INDICE_2023", "INDICE_2025", "VARIACAO_INDICE") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  SELECT
    p23.NOME_UF,
    p23.PERFIL_ASSISTENCIAL AS PERFIL_2023,
    p25.PERFIL_ASSISTENCIAL AS PERFIL_2025,
    p23.INDICE_PRESSAO_ASSISTENCIAL AS INDICE_2023,
    p25.INDICE_PRESSAO_ASSISTENCIAL AS INDICE_2025,

    ROUND(
        p25.INDICE_PRESSAO_ASSISTENCIAL
        - p23.INDICE_PRESSAO_ASSISTENCIAL,
        2
    ) AS VARIACAO_INDICE

FROM ADMIN.VW_PERFIL_ASSISTENCIAL p23
JOIN ADMIN.VW_PERFIL_ASSISTENCIAL p25
    ON p23.NOME_UF = p25.NOME_UF
   AND p23.ANO = 2023
   AND p25.ANO = 2025;
