CREATE OR REPLACE FORCE EDITIONABLE VIEW "ADMIN"."VW_CAPACIDADE_HOSPITALAR" ("UF", "NOME_UF", "ANO_REF", "QTD_ESTABELECIMENTOS", "LEITOS_EXISTENTES", "LEITOS_SUS", "UTI_TOTAL_EXIST", "UTI_TOTAL_SUS", "UTI_ADULTO_EXIST", "UTI_ADULTO_SUS", "UTI_PEDIATRICO_EXIST", "UTI_PEDIATRICO_SUS", "UTI_NEONATAL_EXIST", "UTI_NEONATAL_SUS", "UTI_QUEIMADO_EXIST", "UTI_QUEIMADO_SUS", "UTI_CORONARIANA_EXIST", "UTI_CORONARIANA_SUS") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  SELECT
    UF,
    NOME_UF,
    ANO_REF,

    COUNT(DISTINCT CNES) AS QTD_ESTABELECIMENTOS,

    SUM(NVL(LEITOS_EXISTENTES, 0)) AS LEITOS_EXISTENTES,
    SUM(NVL(LEITOS_SUS, 0)) AS LEITOS_SUS,

    SUM(NVL(UTI_TOTAL_EXIST, 0)) AS UTI_TOTAL_EXIST,
    SUM(NVL(UTI_TOTAL_SUS, 0)) AS UTI_TOTAL_SUS,

    SUM(NVL(UTI_ADULTO_EXIST, 0)) AS UTI_ADULTO_EXIST,
    SUM(NVL(UTI_ADULTO_SUS, 0)) AS UTI_ADULTO_SUS,

    SUM(NVL(UTI_PEDIATRICO_EXIST, 0)) AS UTI_PEDIATRICO_EXIST,
    SUM(NVL(UTI_PEDIATRICO_SUS, 0)) AS UTI_PEDIATRICO_SUS,

    SUM(NVL(UTI_NEONATAL_EXIST, 0)) AS UTI_NEONATAL_EXIST,
    SUM(NVL(UTI_NEONATAL_SUS, 0)) AS UTI_NEONATAL_SUS,

    SUM(NVL(UTI_QUEIMADO_EXIST, 0)) AS UTI_QUEIMADO_EXIST,
    SUM(NVL(UTI_QUEIMADO_SUS, 0)) AS UTI_QUEIMADO_SUS,

    SUM(NVL(UTI_CORONARIANA_EXIST, 0)) AS UTI_CORONARIANA_EXIST,
    SUM(NVL(UTI_CORONARIANA_SUS, 0)) AS UTI_CORONARIANA_SUS

FROM ADMIN.CNES_LEITOS_2023_2025

WHERE COMP = ADD_MONTHS(
    TO_DATE(ANO_REF || '-01-01', 'YYYY-MM-DD'),
    11
)

GROUP BY
    UF,
    NOME_UF,
    ANO_REF;
