CREATE OR REPLACE FORCE EDITIONABLE VIEW "ADMIN"."VW_EVOLUCAO_INDICADORES" ("NOME_UF", "INTERNACOES_2023", "INTERNACOES_2025", "VAR_INTERNACOES", "VAR_INTERNACOES_PCT", "LEITOS_SUS_2023", "LEITOS_SUS_2025", "VAR_LEITOS_SUS", "VAR_LEITOS_SUS_PCT", "LEITOS_10K_2023", "LEITOS_10K_2025", "VAR_LEITOS_10K", "VAR_LEITOS_10K_PCT", "UTI_100K_2023", "UTI_100K_2025", "VAR_UTI_100K", "VAR_UTI_100K_PCT", "DEMANDA_LEITO_2023", "DEMANDA_LEITO_2025", "VAR_DEMANDA_LEITO", "VAR_DEMANDA_LEITO_PCT", "MORTALIDADE_2023", "MORTALIDADE_2025", "VAR_MORTALIDADE", "GASTO_MEDIO_2023", "GASTO_MEDIO_2025", "VAR_GASTO_MEDIO", "VAR_GASTO_MEDIO_PCT", "OBITOS_2023", "OBITOS_2025", "VAR_OBITOS", "VAR_OBITOS_PCT") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  SELECT
    T23.NOME_UF,

    /* =========================
       INTERNAÇÕES
       ========================= */
    T23.TOTAL_INTERNACOES AS INTERNACOES_2023,
    T25.TOTAL_INTERNACOES AS INTERNACOES_2025,

    T25.TOTAL_INTERNACOES - T23.TOTAL_INTERNACOES
        AS VAR_INTERNACOES,

    ROUND(
        (T25.TOTAL_INTERNACOES - T23.TOTAL_INTERNACOES)
        / NULLIF(T23.TOTAL_INTERNACOES, 0) * 100,
        2
    ) AS VAR_INTERNACOES_PCT,

    /* =========================
       LEITOS SUS
       ========================= */
    T23.LEITOS_SUS AS LEITOS_SUS_2023,
    T25.LEITOS_SUS AS LEITOS_SUS_2025,

    T25.LEITOS_SUS - T23.LEITOS_SUS
        AS VAR_LEITOS_SUS,

    ROUND(
        (T25.LEITOS_SUS - T23.LEITOS_SUS)
        / NULLIF(T23.LEITOS_SUS, 0) * 100,
        2
    ) AS VAR_LEITOS_SUS_PCT,

    /* =========================
       LEITOS SUS / 10 MIL HAB.
       ========================= */
    T23.LEITOS_POR_10K_HAB AS LEITOS_10K_2023,
    T25.LEITOS_POR_10K_HAB AS LEITOS_10K_2025,

    ROUND(
        T25.LEITOS_POR_10K_HAB - T23.LEITOS_POR_10K_HAB,
        2
    ) AS VAR_LEITOS_10K,

    ROUND(
        (T25.LEITOS_POR_10K_HAB - T23.LEITOS_POR_10K_HAB)
        / NULLIF(T23.LEITOS_POR_10K_HAB, 0) * 100,
        2
    ) AS VAR_LEITOS_10K_PCT,

    /* =========================
       UTI SUS / 100 MIL HAB.
       ========================= */
    T23.UTI_SUS_100K AS UTI_100K_2023,
    T25.UTI_SUS_100K AS UTI_100K_2025,

    ROUND(
        T25.UTI_SUS_100K - T23.UTI_SUS_100K,
        2
    ) AS VAR_UTI_100K,

    ROUND(
        (T25.UTI_SUS_100K - T23.UTI_SUS_100K)
        / NULLIF(T23.UTI_SUS_100K, 0) * 100,
        2
    ) AS VAR_UTI_100K_PCT,

    /* =========================
       DEMANDA POR LEITO
       ========================= */
    T23.INTERNACOES_POR_LEITO AS DEMANDA_LEITO_2023,
    T25.INTERNACOES_POR_LEITO AS DEMANDA_LEITO_2025,

    ROUND(
        T25.INTERNACOES_POR_LEITO - T23.INTERNACOES_POR_LEITO,
        2
    ) AS VAR_DEMANDA_LEITO,

    ROUND(
        (T25.INTERNACOES_POR_LEITO - T23.INTERNACOES_POR_LEITO)
        / NULLIF(T23.INTERNACOES_POR_LEITO, 0) * 100,
        2
    ) AS VAR_DEMANDA_LEITO_PCT,

    /* =========================
       MORTALIDADE
       ========================= */
    T23.TAXA_MORTALIDADE_HOSPITALAR AS MORTALIDADE_2023,
    T25.TAXA_MORTALIDADE_HOSPITALAR AS MORTALIDADE_2025,

    ROUND(
        T25.TAXA_MORTALIDADE_HOSPITALAR
        - T23.TAXA_MORTALIDADE_HOSPITALAR,
        2
    ) AS VAR_MORTALIDADE,

    /* =========================
       GASTO MÉDIO
       ========================= */
    T23.GASTO_MEDIO_INTERNACAO AS GASTO_MEDIO_2023,
    T25.GASTO_MEDIO_INTERNACAO AS GASTO_MEDIO_2025,

    ROUND(
        T25.GASTO_MEDIO_INTERNACAO
        - T23.GASTO_MEDIO_INTERNACAO,
        2
    ) AS VAR_GASTO_MEDIO,

    ROUND(
        (T25.GASTO_MEDIO_INTERNACAO - T23.GASTO_MEDIO_INTERNACAO)
        / NULLIF(T23.GASTO_MEDIO_INTERNACAO, 0) * 100,
        2
    ) AS VAR_GASTO_MEDIO_PCT,

    /* =========================
       ÓBITOS SIH
       ========================= */
    O23.OBITOS_2023,
    O25.OBITOS_2025,

    O25.OBITOS_2025 - O23.OBITOS_2023
        AS VAR_OBITOS,

    ROUND(
        (O25.OBITOS_2025 - O23.OBITOS_2023)
        / NULLIF(O23.OBITOS_2023, 0) * 100,
        2
    ) AS VAR_OBITOS_PCT

FROM
    ADMIN.VW_INDICADORES_TERRITORIAIS T23

JOIN
    ADMIN.VW_INDICADORES_TERRITORIAIS T25
    ON T25.NOME_UF = T23.NOME_UF
   AND T25.ANO = 2025

JOIN
(
    SELECT
        NOME_UF,
        SUM(OBITOS) AS OBITOS_2023
    FROM ADMIN.VW_OBITOS_MENSAIS
    WHERE ANO_REF = 2023
    GROUP BY NOME_UF
) O23
    ON O23.NOME_UF = T23.NOME_UF

JOIN
(
    SELECT
        NOME_UF,
        SUM(OBITOS) AS OBITOS_2025
    FROM ADMIN.VW_OBITOS_MENSAIS
    WHERE ANO_REF = 2025
    GROUP BY NOME_UF
) O25
    ON O25.NOME_UF = T23.NOME_UF

WHERE
    T23.ANO = 2023;
