CREATE OR REPLACE FORCE EDITIONABLE VIEW "ADMIN"."VW_INDICADORES_TERRITORIAIS" ("NOME_UF", "ANO", "TOTAL_INTERNACOES", "MEDIA_PERMANENCIA_ANO", "LEITOS_SUS", "LEITOS_POR_10K_HAB", "INTERNACOES_POR_LEITO", "TAXA_MORTALIDADE_HOSPITALAR", "GASTO_MEDIO_INTERNACAO", "QTD_ESTABELECIMENTOS", "LEITOS_EXISTENTES", "LEITOS_SUS_CNES", "UTI_TOTAL_EXIST", "UTI_TOTAL_SUS", "POPULACAO", "UTI_SUS_100K") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  SELECT
    D.NOME_UF,
    D.ANO,

    -- Demanda
    D.TOTAL_INTERNACOES,
    D.MEDIA_PERMANENCIA_ANO,

    -- Indicadores já existentes no dataset
    D.LEITOS_SUS,
    D.LEITOS_POR_10K_HAB,
    D.INTERNACOES_POR_LEITO,
    D.TAXA_MORTALIDADE_HOSPITALAR,
    D.GASTO_MEDIO_INTERNACAO,

    -- Capacidade CNES
    C.QTD_ESTABELECIMENTOS,
    C.LEITOS_EXISTENTES,
    C.LEITOS_SUS AS LEITOS_SUS_CNES,
    C.UTI_TOTAL_EXIST,
    C.UTI_TOTAL_SUS,

    -- População oficial IBGE
    P.POPULACAO,

    -- Novo indicador
    ROUND(
        C.UTI_TOTAL_SUS / NULLIF(P.POPULACAO, 0) * 100000,
        2
    ) AS UTI_SUS_100K

FROM ADMIN.DATASET_UNIFICADO_UF_2023_2025 D

JOIN ADMIN.VW_CAPACIDADE_HOSPITALAR C
    ON UPPER(TRIM(C.NOME_UF)) = UPPER(TRIM(D.NOME_UF))
   AND C.ANO_REF = D.ANO

JOIN ADMIN.IBGE_POPULACAO_UF_2023_2025 P
    ON P.CO_UF_IBGE = D.CO_UF_IBGE
   AND P.ANO_REF = D.ANO;
