CREATE OR REPLACE FORCE EDITIONABLE VIEW "ADMIN"."VW_INTELIGENCIA_ASSISTENCIAL" ("NOME_UF", "ANO", "PERFIL_ASSISTENCIAL", "INDICE_PRESSAO_ASSISTENCIAL", "TOTAL_INTERNACOES", "INTERNACOES_POR_LEITO", "LEITOS_POR_10K_HAB", "UTI_SUS_100K", "LEITOS_SUS_CNES", "MEDIANA_PRESSAO", "MEDIANA_DEMANDA", "MEDIANA_LEITOS", "MEDIANA_UTI", "PONTO_PRESSAO_SOBRECARGA", "PONTO_DEMANDA_SOBRECARGA", "PONTO_LEITOS_SOBRECARGA", "PONTO_UTI_SOBRECARGA", "SCORE_SOBRECARGA", "CENARIO_SOBRECARGA", "RANK_PRESSAO", "RANK_CAPACIDADE_SOBRECARGA", "VARIACAO_PRESSAO_ANUAL", "VARIACAO_PRESSAO_PERIODO", "PONTO_PRESSAO_CAPACIDADE", "PONTO_DEMANDA_CAPACIDADE", "PONTO_LEITOS_CAPACIDADE", "PONTO_UTI_CAPACIDADE", "SCORE_SUBUTILIZACAO", "SCORE_CAPACIDADE", "CENARIO_CAPACIDADE", "RANK_MAIOR_CAPACIDADE", "RANK_MENOR_CAPACIDADE") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  WITH SOBRECARGA AS (
    SELECT
        NOME_UF,
        ANO,
        PERFIL_ASSISTENCIAL,
        INDICE_PRESSAO_ASSISTENCIAL,
        TOTAL_INTERNACOES,
        INTERNACOES_POR_LEITO,
        LEITOS_POR_10K_HAB,
        UTI_SUS_100K,

        MEDIANA_PRESSAO,
        MEDIANA_DEMANDA,
        MEDIANA_LEITOS,
        MEDIANA_UTI,

        PONTO_PRESSAO,
        PONTO_DEMANDA,
        PONTO_LEITOS,
        PONTO_UTI,

        SCORE_SOBRECARGA,
        CENARIO_SOBRECARGA,
        RANK_PRESSAO,
        RANK_CAPACIDADE,

        VARIACAO_PRESSAO_ANUAL,
        VARIACAO_PRESSAO_PERIODO

    FROM ADMIN.VW_SIMULACAO_SOBRECARGA
),

CAPACIDADE AS (
    SELECT
        NOME_UF,
        ANO,

        PERFIL_ASSISTENCIAL,
        INDICE_PRESSAO_ASSISTENCIAL,
        TOTAL_INTERNACOES,
        LEITOS_SUS_CNES,
        LEITOS_POR_10K_HAB,
        UTI_SUS_100K,
        INTERNACOES_POR_LEITO,

        PONTO_PRESSAO,
        PONTO_DEMANDA,
        PONTO_LEITOS,
        PONTO_UTI,

        SCORE_SUBUTILIZACAO,
        SCORE_CAPACIDADE,
        CENARIO_SUBUTILIZACAO,

        RANK_MAIOR_CAPACIDADE,
        RANK_MENOR_CAPACIDADE

    FROM ADMIN.VW_SIMULACAO_SUBUTILIZACAO
)

SELECT
    S.NOME_UF,
    S.ANO,

    /* Contexto assistencial */
    COALESCE(
        S.PERFIL_ASSISTENCIAL,
        C.PERFIL_ASSISTENCIAL
    ) AS PERFIL_ASSISTENCIAL,

    COALESCE(
        S.INDICE_PRESSAO_ASSISTENCIAL,
        C.INDICE_PRESSAO_ASSISTENCIAL
    ) AS INDICE_PRESSAO_ASSISTENCIAL,

    COALESCE(
        S.TOTAL_INTERNACOES,
        C.TOTAL_INTERNACOES
    ) AS TOTAL_INTERNACOES,

    COALESCE(
        S.INTERNACOES_POR_LEITO,
        C.INTERNACOES_POR_LEITO
    ) AS INTERNACOES_POR_LEITO,

    COALESCE(
        S.LEITOS_POR_10K_HAB,
        C.LEITOS_POR_10K_HAB
    ) AS LEITOS_POR_10K_HAB,

    COALESCE(
        S.UTI_SUS_100K,
        C.UTI_SUS_100K
    ) AS UTI_SUS_100K,

    C.LEITOS_SUS_CNES,

    /* Sobrecarga */
    S.MEDIANA_PRESSAO,
    S.MEDIANA_DEMANDA,
    S.MEDIANA_LEITOS,
    S.MEDIANA_UTI,

    S.PONTO_PRESSAO AS PONTO_PRESSAO_SOBRECARGA,
    S.PONTO_DEMANDA AS PONTO_DEMANDA_SOBRECARGA,
    S.PONTO_LEITOS AS PONTO_LEITOS_SOBRECARGA,
    S.PONTO_UTI AS PONTO_UTI_SOBRECARGA,

    S.SCORE_SOBRECARGA,
    S.CENARIO_SOBRECARGA,
    S.RANK_PRESSAO,
    S.RANK_CAPACIDADE AS RANK_CAPACIDADE_SOBRECARGA,

    S.VARIACAO_PRESSAO_ANUAL,
    S.VARIACAO_PRESSAO_PERIODO,

    /* Capacidade relativa */
    C.PONTO_PRESSAO AS PONTO_PRESSAO_CAPACIDADE,
    C.PONTO_DEMANDA AS PONTO_DEMANDA_CAPACIDADE,
    C.PONTO_LEITOS AS PONTO_LEITOS_CAPACIDADE,
    C.PONTO_UTI AS PONTO_UTI_CAPACIDADE,

    C.SCORE_SUBUTILIZACAO,
    C.SCORE_CAPACIDADE,

    C.CENARIO_SUBUTILIZACAO
        AS CENARIO_CAPACIDADE,

    C.RANK_MAIOR_CAPACIDADE,
    C.RANK_MENOR_CAPACIDADE

FROM SOBRECARGA S

LEFT JOIN CAPACIDADE C
    ON C.NOME_UF = S.NOME_UF
   AND C.ANO = S.ANO;
