CREATE OR REPLACE FORCE EDITIONABLE VIEW "ADMIN"."VW_OBITOS_MENSAIS" ("CO_UF_IBGE", "NOME_UF", "ANO_REF", "MES_REF", "OBITOS") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  SELECT
    CO_UF_IBGE,
    NOME_UF,
    ANO_REF,
    MES_REF,
    OBITOS
FROM ADMIN.OBITOS_SIH_MENSAL_UF_2023_2025;
