CREATE OR REPLACE FORCE EDITIONABLE VIEW "ADMIN"."VW_PERFIL_HOSPITAL" ("ANO", "NOME_UF", "CO_UF_IBGE", "UF", "MUNICIPIO", "CNES", "NOME_ESTABELECIMENTO", "TP_GESTAO", "TIPO_UNIDADE", "NATUREZA_JURIDICA", "PORTE", "LEITOS_EXISTENTES", "LEITOS_SUS", "UTI_TOTAL_EXIST", "UTI_TOTAL_SUS", "UTI_ADULTO_EXIST", "UTI_ADULTO_SUS", "UTI_PEDIATRICO_EXIST", "UTI_PEDIATRICO_SUS", "UTI_NEONATAL_EXIST", "UTI_NEONATAL_SUS", "UTI_QUEIMADO_EXIST", "UTI_QUEIMADO_SUS", "UTI_CORONARIANA_EXIST", "UTI_CORONARIANA_SUS") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  SELECT
    C."ANO_REF" AS "ANO",
    C."NOME_UF",
    C."CO_IBGE" AS "CO_UF_IBGE",
    C."UF",
    C."MUNICIPIO",
    C."CNES",
    C."NOME_ESTABELECIMENTO",
    C."TP_GESTAO",
    C."DS_TIPO_UNIDADE" AS "TIPO_UNIDADE",
    C."DESC_NATUREZA_JURIDICA" AS "NATUREZA_JURIDICA",
    C."PORTE",

    C."LEITOS_EXISTENTES",
    C."LEITOS_SUS",

    C."UTI_TOTAL_EXIST",
    C."UTI_TOTAL_SUS",

    C."UTI_ADULTO_EXIST",
    C."UTI_ADULTO_SUS",

    C."UTI_PEDIATRICO_EXIST",
    C."UTI_PEDIATRICO_SUS",

    C."UTI_NEONATAL_EXIST",
    C."UTI_NEONATAL_SUS",

    C."UTI_QUEIMADO_EXIST",
    C."UTI_QUEIMADO_SUS",

    C."UTI_CORONARIANA_EXIST",
    C."UTI_CORONARIANA_SUS"

FROM ADMIN."CNES_LEITOS_2023_2025" C;
