CREATE OR REPLACE FORCE EDITIONABLE VIEW "ADMIN"."VW_PERFIL_HOSPITAL_ATUAL" ("ANO", "NOME_UF", "CO_UF_IBGE", "UF", "MUNICIPIO", "CNES", "NOME_ESTABELECIMENTO", "TP_GESTAO", "TIPO_UNIDADE", "NATUREZA_JURIDICA", "PORTE", "LEITOS_EXISTENTES", "LEITOS_SUS", "UTI_TOTAL_EXIST", "UTI_TOTAL_SUS", "UTI_ADULTO_EXIST", "UTI_ADULTO_SUS", "UTI_PEDIATRICO_EXIST", "UTI_PEDIATRICO_SUS", "UTI_NEONATAL_EXIST", "UTI_NEONATAL_SUS", "UTI_QUEIMADO_EXIST", "UTI_QUEIMADO_SUS", "UTI_CORONARIANA_EXIST", "UTI_CORONARIANA_SUS") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  SELECT
    ANO,
    NOME_UF,
    CO_UF_IBGE,
    UF,
    MUNICIPIO,
    CNES,
    NOME_ESTABELECIMENTO,
    TP_GESTAO,
    TIPO_UNIDADE,
    NATUREZA_JURIDICA,
    PORTE,
    LEITOS_EXISTENTES,
    LEITOS_SUS,
    UTI_TOTAL_EXIST,
    UTI_TOTAL_SUS,
    UTI_ADULTO_EXIST,
    UTI_ADULTO_SUS,
    UTI_PEDIATRICO_EXIST,
    UTI_PEDIATRICO_SUS,
    UTI_NEONATAL_EXIST,
    UTI_NEONATAL_SUS,
    UTI_QUEIMADO_EXIST,
    UTI_QUEIMADO_SUS,
    UTI_CORONARIANA_EXIST,
    UTI_CORONARIANA_SUS
FROM (
    SELECT
        H.*,
        ROW_NUMBER() OVER (
            PARTITION BY CNES
            ORDER BY ANO DESC
        ) AS RN
    FROM ADMIN.VW_PERFIL_HOSPITAL H
    WHERE CNES IS NOT NULL
)
WHERE RN = 1;
