CREATE OR REPLACE FORCE EDITIONABLE VIEW "ADMIN"."VW_PERFIL_ATENDIMENTO" ("NOME_UF", "ANO", "TIPO_UNIDADE_PREDOMINANTE", "PORTE_PREDOMINANTE", "QTD_ESTABELECIMENTOS", "LEITOS_EXISTENTES", "LEITOS_SUS_CNES", "UTI_TOTAL_EXIST", "UTI_TOTAL_SUS", "TOTAL_INTERNACOES", "INTERNACOES_POR_LEITO", "LEITOS_POR_10K_HAB", "UTI_SUS_100K", "INDICE_PRESSAO_ASSISTENCIAL", "PERFIL_ASSISTENCIAL", "TAXA_MORTALIDADE_HOSPITALAR", "GASTO_MEDIO_INTERNACAO") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  WITH TIPO_PREDOMINANTE AS (
    SELECT
        NOME_UF,
        ANO_REF,
        DS_TIPO_UNIDADE,
        COUNT(DISTINCT CNES) AS QTD,
        ROW_NUMBER() OVER (
            PARTITION BY NOME_UF, ANO_REF
            ORDER BY COUNT(DISTINCT CNES) DESC,
                     DS_TIPO_UNIDADE
        ) AS RN
    FROM ADMIN.CNES_LEITOS_2023_2025
    WHERE COMP = ADD_MONTHS(
        TO_DATE(ANO_REF || '-01-01', 'YYYY-MM-DD'),
        11
    )
    GROUP BY
        NOME_UF,
        ANO_REF,
        DS_TIPO_UNIDADE
),

PORTE_PREDOMINANTE AS (
    SELECT
        NOME_UF,
        ANO_REF,
        PORTE,
        COUNT(DISTINCT CNES) AS QTD,
        ROW_NUMBER() OVER (
            PARTITION BY NOME_UF, ANO_REF
            ORDER BY COUNT(DISTINCT CNES) DESC,
                     PORTE
        ) AS RN
    FROM ADMIN.CNES_LEITOS_2023_2025
    WHERE COMP = ADD_MONTHS(
        TO_DATE(ANO_REF || '-01-01', 'YYYY-MM-DD'),
        11
    )
    GROUP BY
        NOME_UF,
        ANO_REF,
        PORTE
)

SELECT
    P.NOME_UF,
    P.ANO,

    /* ESTRUTURA CNES */
    T.DS_TIPO_UNIDADE AS TIPO_UNIDADE_PREDOMINANTE,
    PO.PORTE AS PORTE_PREDOMINANTE,

    /* CAPACIDADE */
    I.QTD_ESTABELECIMENTOS,
    I.LEITOS_EXISTENTES,
    I.LEITOS_SUS_CNES,
    I.UTI_TOTAL_EXIST,
    I.UTI_TOTAL_SUS,

    /* DEMANDA */
    P.TOTAL_INTERNACOES,
    P.INTERNACOES_POR_LEITO,

    /* OFERTA RELATIVA */
    P.LEITOS_POR_10K_HAB,
    I.UTI_SUS_100K,

    /* PRESSÃO */
    P.INDICE_PRESSAO_ASSISTENCIAL,
    P.PERFIL_ASSISTENCIAL,

    /* COMPLEMENTARES */
    I.TAXA_MORTALIDADE_HOSPITALAR,
    I.GASTO_MEDIO_INTERNACAO

FROM ADMIN.VW_PERFIL_ASSISTENCIAL P

JOIN ADMIN.VW_INDICADORES_TERRITORIAIS I
    ON UPPER(TRIM(I.NOME_UF)) = UPPER(TRIM(P.NOME_UF))
   AND I.ANO = P.ANO

LEFT JOIN TIPO_PREDOMINANTE T
    ON UPPER(TRIM(T.NOME_UF)) = UPPER(TRIM(P.NOME_UF))
   AND T.ANO_REF = P.ANO
   AND T.RN = 1

LEFT JOIN PORTE_PREDOMINANTE PO
    ON UPPER(TRIM(PO.NOME_UF)) = UPPER(TRIM(P.NOME_UF))
   AND PO.ANO_REF = P.ANO
   AND PO.RN = 1;
