CREATE OR REPLACE FORCE EDITIONABLE VIEW "ADMIN"."VW_SIMULACAO_SOBRECARGA_V2" ("NOME_UF", "ANO", "PERFIL_ASSISTENCIAL", "INDICE_PRESSAO_ASSISTENCIAL", "TOTAL_INTERNACOES", "INTERNACOES_POR_LEITO", "LEITOS_POR_10K_HAB", "UTI_SUS_100K", "MEDIANA_PRESSAO", "MEDIANA_DEMANDA", "MEDIANA_LEITOS", "MEDIANA_UTI", "PONTO_PRESSAO", "PONTO_DEMANDA", "PONTO_LEITOS", "PONTO_UTI", "SCORE_SOBRECARGA", "CENARIO_SOBRECARGA", "RANK_PRESSAO", "RANK_CAPACIDADE", "VARIACAO_PRESSAO_ANUAL", "VARIACAO_PRESSAO_PERIODO") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  WITH BASE AS (
    SELECT
        P.NOME_UF,
        P.ANO,
        P.PERFIL_ASSISTENCIAL,
        P.INDICE_PRESSAO_ASSISTENCIAL,
        P.TOTAL_INTERNACOES,
        P.INTERNACOES_POR_LEITO,
        P.LEITOS_POR_10K_HAB,
        P.UTI_SUS_100K
    FROM ADMIN.VW_PERFIL_ASSISTENCIAL P
),
REFERENCIAS AS (
    SELECT
        B.*,

        MEDIAN(INDICE_PRESSAO_ASSISTENCIAL) OVER (
            PARTITION BY ANO
        ) AS MEDIANA_PRESSAO,

        MEDIAN(INTERNACOES_POR_LEITO) OVER (
            PARTITION BY ANO
        ) AS MEDIANA_DEMANDA,

        MEDIAN(LEITOS_POR_10K_HAB) OVER (
            PARTITION BY ANO
        ) AS MEDIANA_LEITOS,

        MEDIAN(UTI_SUS_100K) OVER (
            PARTITION BY ANO
        ) AS MEDIANA_UTI,

ROW_NUMBER() OVER (
    PARTITION BY ANO
    ORDER BY
        INDICE_PRESSAO_ASSISTENCIAL DESC,
        INTERNACOES_POR_LEITO DESC,
        NOME_UF
) AS RANK_PRESSAO,

ROW_NUMBER() OVER (
    PARTITION BY ANO
    ORDER BY
        LEITOS_POR_10K_HAB DESC,
        UTI_SUS_100K DESC,
        NOME_UF
) AS RANK_CAPACIDADE

    FROM BASE B
),
PONTOS AS (
    SELECT
        R.*,

        CASE
            WHEN INDICE_PRESSAO_ASSISTENCIAL > MEDIANA_PRESSAO
            THEN 1 ELSE 0
        END AS PONTO_PRESSAO,

        CASE
            WHEN INTERNACOES_POR_LEITO > MEDIANA_DEMANDA
            THEN 1 ELSE 0
        END AS PONTO_DEMANDA,

        CASE
            WHEN LEITOS_POR_10K_HAB < MEDIANA_LEITOS
            THEN 1 ELSE 0
        END AS PONTO_LEITOS,

        CASE
            WHEN UTI_SUS_100K < MEDIANA_UTI
            THEN 1 ELSE 0
        END AS PONTO_UTI

    FROM REFERENCIAS R
),
SCORES AS (
    SELECT
        P.*,

        (
            PONTO_PRESSAO
          + PONTO_DEMANDA
          + PONTO_LEITOS
          + PONTO_UTI
        ) AS SCORE_SOBRECARGA

    FROM PONTOS P
),
HISTORICO AS (
    SELECT
        S.*,

        LAG(INDICE_PRESSAO_ASSISTENCIAL) OVER (
            PARTITION BY NOME_UF
            ORDER BY ANO
        ) AS PRESSAO_ANO_ANTERIOR,

        FIRST_VALUE(INDICE_PRESSAO_ASSISTENCIAL) OVER (
            PARTITION BY NOME_UF
            ORDER BY ANO
            ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING
        ) AS PRESSAO_INICIAL

    FROM SCORES S
)
SELECT
    NOME_UF,
    ANO,
    PERFIL_ASSISTENCIAL,

    ROUND(INDICE_PRESSAO_ASSISTENCIAL, 2) AS INDICE_PRESSAO_ASSISTENCIAL,
    TOTAL_INTERNACOES,
    ROUND(INTERNACOES_POR_LEITO, 2) AS INTERNACOES_POR_LEITO,
    ROUND(LEITOS_POR_10K_HAB, 2) AS LEITOS_POR_10K_HAB,
    ROUND(UTI_SUS_100K, 2) AS UTI_SUS_100K,

    ROUND(MEDIANA_PRESSAO, 2) AS MEDIANA_PRESSAO,
    ROUND(MEDIANA_DEMANDA, 2) AS MEDIANA_DEMANDA,
    ROUND(MEDIANA_LEITOS, 2) AS MEDIANA_LEITOS,
    ROUND(MEDIANA_UTI, 2) AS MEDIANA_UTI,

    PONTO_PRESSAO,
    PONTO_DEMANDA,
    PONTO_LEITOS,
    PONTO_UTI,

    SCORE_SOBRECARGA,

    CASE
        WHEN SCORE_SOBRECARGA <= 1
            THEN 'SEM SINAL RELEVANTE'
        WHEN SCORE_SOBRECARGA = 2
            THEN 'ATENCAO'
        WHEN SCORE_SOBRECARGA = 3
            THEN 'SOBRECARGA PROVAVEL'
        ELSE
            'SOBRECARGA CRITICA'
    END AS CENARIO_SOBRECARGA,

    RANK_PRESSAO,
    RANK_CAPACIDADE,

    ROUND(
        INDICE_PRESSAO_ASSISTENCIAL - PRESSAO_ANO_ANTERIOR,
        2
    ) AS VARIACAO_PRESSAO_ANUAL,

    ROUND(
        INDICE_PRESSAO_ASSISTENCIAL - PRESSAO_INICIAL,
        2
    ) AS VARIACAO_PRESSAO_PERIODO

FROM HISTORICO;
