CREATE OR REPLACE FORCE EDITIONABLE VIEW "ADMIN"."VW_TRANSICAO_PERFIL_ASSISTENCIAL" ("NOME_UF", "PERFIL_2023", "PERFIL_2025", "INDICE_2023", "INDICE_2025", "VARIACAO_INDICE") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  SELECT
    p23.NOME_UF,
    p23.PERFIL_ASSISTENCIAL AS PERFIL_2023,
    p25.PERFIL_ASSISTENCIAL AS PERFIL_2025,
    p23.INDICE_PRESSAO_ASSISTENCIAL AS INDICE_2023,
    p25.INDICE_PRESSAO_ASSISTENCIAL AS INDICE_2025,

    ROUND(
        p25.INDICE_PRESSAO_ASSISTENCIAL
        - p23.INDICE_PRESSAO_ASSISTENCIAL,
        2
    ) AS VARIACAO_INDICE

FROM ADMIN.VW_PERFIL_ASSISTENCIAL p23
JOIN ADMIN.VW_PERFIL_ASSISTENCIAL p25
    ON p23.NOME_UF = p25.NOME_UF
   AND p23.ANO = 2023
   AND p25.ANO = 2025;
